<script>
    import SelectProperty from './SelectProperty.svelte';

    export let value;
</script>
<SelectProperty {...$$restProps} options={{
    'Dropped Item': 'DROPPED_ITEM',
    'Experience Orb': 'EXPERIENCE_ORB',
    'Area Effect Cloud': 'AREA_EFFECT_CLOUD',
    'Elder Guardian': 'ELDER_GUARDIAN',
    'Wither Skeleton': 'WITHER_SKELETON',
    'Stray': 'STRAY',
    'Egg': 'EGG',
    'Leash Hitch': 'LEASH_HITCH',
    'Painting': 'PAINTING',
    'Arrow': 'ARROW',
    'Snowball': 'SNOWBALL',
    'Fireball': 'FIREBALL',
    'Small Fireball': 'SMALL_FIREBALL',
    'Ender Pearl': 'ENDER_PEARL',
    'Ender Signal': 'ENDER_SIGNAL',
    'Splash Potion': 'SPLASH_POTION',
    'Thrown Exp Bottle': 'THROWN_EXP_BOTTLE',
    'Item Frame': 'ITEM_FRAME',
    'Wither Skull': 'WITHER_SKULL',
    'Primed Tnt': 'PRIMED_TNT',
    'Falling Block': 'FALLING_BLOCK',
    'Firework': 'FIREWORK',
    'Husk': 'HUSK',
    'Spectral Arrow': 'SPECTRAL_ARROW',
    'Shulker Bullet': 'SHULKER_BULLET',
    'Dragon Fireball': 'DRAGON_FIREBALL',
    'Zombie Villager': 'ZOMBIE_VILLAGER',
    'Skeleton Horse': 'SKELETON_HORSE',
    'Zombie Horse': 'ZOMBIE_HORSE',
    'Armor Stand': 'ARMOR_STAND',
    'Donkey': 'DONKEY',
    'Mule': 'MULE',
    'Evoker Fangs': 'EVOKER_FANGS',
    'Evoker': 'EVOKER',
    'Vex': 'VEX',
    'Vindicator': 'VINDICATOR',
    'Illusioner': 'ILLUSIONER',
    'Minecart Command': 'MINECART_COMMAND',
    'Boat': 'BOAT',
    'Minecart': 'MINECART',
    'Minecart Chest': 'MINECART_CHEST',
    'Minecart Furnace': 'MINECART_FURNACE',
    'Minecart Tnt': 'MINECART_TNT',
    'Minecart Hopper': 'MINECART_HOPPER',
    'Minecart Mob Spawner': 'MINECART_MOB_SPAWNER',
    'Creeper': 'CREEPER',
    'Skeleton': 'SKELETON',
    'Spider': 'SPIDER',
    'Giant': 'GIANT',
    'Zombie': 'ZOMBIE',
    'Slime': 'SLIME',
    'Ghast': 'GHAST',
    'Zombified Piglin': 'ZOMBIFIED_PIGLIN',
    'Enderman': 'ENDERMAN',
    'Cave Spider': 'CAVE_SPIDER',
    'Silverfish': 'SILVERFISH',
    'Blaze': 'BLAZE',
    'Magma Cube': 'MAGMA_CUBE',
    'Ender Dragon': 'ENDER_DRAGON',
    'Wither': 'WITHER',
    'Bat': 'BAT',
    'Witch': 'WITCH',
    'Endermite': 'ENDERMITE',
    'Guardian': 'GUARDIAN',
    'Shulker': 'SHULKER',
    'Pig': 'PIG',
    'Sheep': 'SHEEP',
    'Cow': 'COW',
    'Chicken': 'CHICKEN',
    'Squid': 'SQUID',
    'Wolf': 'WOLF',
    'Mushroom Cow': 'MUSHROOM_COW',
    'Snowman': 'SNOWMAN',
    'Ocelot': 'OCELOT',
    'Iron Golem': 'IRON_GOLEM',
    'Horse': 'HORSE',
    'Rabbit': 'RABBIT',
    'Polar Bear': 'POLAR_BEAR',
    'Llama': 'LLAMA',
    'Llama Spit': 'LLAMA_SPIT',
    'Parrot': 'PARROT',
    'Villager': 'VILLAGER',
    'Ender Crystal': 'ENDER_CRYSTAL',
    'Turtle': 'TURTLE',
    'Phantom': 'PHANTOM',
    'Trident': 'TRIDENT',
    'Cod': 'COD',
    'Salmon': 'SALMON',
    'Pufferfish': 'PUFFERFISH',
    'Tropical Fish': 'TROPICAL_FISH',
    'Drowned': 'DROWNED',
    'Dolphin': 'DOLPHIN',
    'Cat': 'CAT',
    'Panda': 'PANDA',
    'Pillager': 'PILLAGER',
    'Ravager': 'RAVAGER',
    'Trader Llama': 'TRADER_LLAMA',
    'Wandering Trader': 'WANDERING_TRADER',
    'Fox': 'FOX',
    'Bee': 'BEE',
    'Hoglin': 'HOGLIN',
    'Piglin': 'PIGLIN',
    'Strider': 'STRIDER',
    'Zoglin': 'ZOGLIN',
    'Piglin Brute': 'PIGLIN_BRUTE',
    'Axolotl': 'AXOLOTL',
    'Glow Item Frame': 'GLOW_ITEM_FRAME',
    'Glow Squid': 'GLOW_SQUID',
    'Goat': 'GOAT',
    'Marker': 'MARKER',
    'Allay': 'ALLAY',
    'Chest Boat': 'CHEST_BOAT',
    'Frog': 'FROG',
    'Tadpole': 'TADPOLE',
    'Warden': 'WARDEN',
    'Fishing Hook': 'FISHING_HOOK',
    'Lightning': 'LIGHTNING',
    'Player': 'PLAYER'
}} bind:value><slot/></SelectProperty>
