<script>
    export let value;
</script>

<select class="form-select" bind:value>
    <option value="STONE">Stone</option>
    <option value="GRANITE">Granite</option>
    <option value="POLISHED_GRANITE">Polished Granite</option>
    <option value="DIORITE">Diorite</option>
    <option value="POLISHED_DIORITE">Polished Diorite</option>
    <option value="ANDESITE">Andesite</option>
    <option value="POLISHED_ANDESITE">Polished Andesite</option>
    <option value="DEEPSLATE">Deepslate</option>
    <option value="COBBLED_DEEPSLATE">Cobbled Deepslate</option>
    <option value="POLISHED_DEEPSLATE">Polished Deepslate</option>
    <option value="CALCITE">Calcite</option>
    <option value="TUFF">Tuff</option>
    <option value="DRIPSTONE_BLOCK">Dripstone Block</option>
    <option value="GRASS_BLOCK">Grass Block</option>
    <option value="DIRT">Dirt</option>
    <option value="COARSE_DIRT">Coarse Dirt</option>
    <option value="PODZOL">Podzol</option>
    <option value="ROOTED_DIRT">Rooted Dirt</option>
    <option value="MUD">Mud</option>
    <option value="CRIMSON_NYLIUM">Crimson Nylium</option>
    <option value="WARPED_NYLIUM">Warped Nylium</option>
    <option value="COBBLESTONE">Cobblestone</option>
    <option value="OAK_PLANKS">Oak Planks</option>
    <option value="SPRUCE_PLANKS">Spruce Planks</option>
    <option value="BIRCH_PLANKS">Birch Planks</option>
    <option value="JUNGLE_PLANKS">Jungle Planks</option>
    <option value="ACACIA_PLANKS">Acacia Planks</option>
    <option value="DARK_OAK_PLANKS">Dark Oak Planks</option>
    <option value="MANGROVE_PLANKS">Mangrove Planks</option>
    <option value="CRIMSON_PLANKS">Crimson Planks</option>
    <option value="WARPED_PLANKS">Warped Planks</option>
    <option value="OAK_SAPLING">Oak Sapling</option>
    <option value="SPRUCE_SAPLING">Spruce Sapling</option>
    <option value="BIRCH_SAPLING">Birch Sapling</option>
    <option value="JUNGLE_SAPLING">Jungle Sapling</option>
    <option value="ACACIA_SAPLING">Acacia Sapling</option>
    <option value="DARK_OAK_SAPLING">Dark Oak Sapling</option>
    <option value="MANGROVE_PROPAGULE">Mangrove Propagule</option>
    <option value="BEDROCK">Bedrock</option>
    <option value="SAND">Sand</option>
    <option value="RED_SAND">Red Sand</option>
    <option value="GRAVEL">Gravel</option>
    <option value="COAL_ORE">Coal Ore</option>
    <option value="DEEPSLATE_COAL_ORE">Deepslate Coal Ore</option>
    <option value="IRON_ORE">Iron Ore</option>
    <option value="DEEPSLATE_IRON_ORE">Deepslate Iron Ore</option>
    <option value="COPPER_ORE">Copper Ore</option>
    <option value="DEEPSLATE_COPPER_ORE">Deepslate Copper Ore</option>
    <option value="GOLD_ORE">Gold Ore</option>
    <option value="DEEPSLATE_GOLD_ORE">Deepslate Gold Ore</option>
    <option value="REDSTONE_ORE">Redstone Ore</option>
    <option value="DEEPSLATE_REDSTONE_ORE">Deepslate Redstone Ore</option>
    <option value="EMERALD_ORE">Emerald Ore</option>
    <option value="DEEPSLATE_EMERALD_ORE">Deepslate Emerald Ore</option>
    <option value="LAPIS_ORE">Lapis Ore</option>
    <option value="DEEPSLATE_LAPIS_ORE">Deepslate Lapis Ore</option>
    <option value="DIAMOND_ORE">Diamond Ore</option>
    <option value="DEEPSLATE_DIAMOND_ORE">Deepslate Diamond Ore</option>
    <option value="NETHER_GOLD_ORE">Nether Gold Ore</option>
    <option value="NETHER_QUARTZ_ORE">Nether Quartz Ore</option>
    <option value="ANCIENT_DEBRIS">Ancient Debris</option>
    <option value="COAL_BLOCK">Coal Block</option>
    <option value="RAW_IRON_BLOCK">Raw Iron Block</option>
    <option value="RAW_COPPER_BLOCK">Raw Copper Block</option>
    <option value="RAW_GOLD_BLOCK">Raw Gold Block</option>
    <option value="AMETHYST_BLOCK">Amethyst Block</option>
    <option value="BUDDING_AMETHYST">Budding Amethyst</option>
    <option value="IRON_BLOCK">Iron Block</option>
    <option value="COPPER_BLOCK">Copper Block</option>
    <option value="GOLD_BLOCK">Gold Block</option>
    <option value="DIAMOND_BLOCK">Diamond Block</option>
    <option value="NETHERITE_BLOCK">Netherite Block</option>
    <option value="EXPOSED_COPPER">Exposed Copper</option>
    <option value="WEATHERED_COPPER">Weathered Copper</option>
    <option value="OXIDIZED_COPPER">Oxidized Copper</option>
    <option value="CUT_COPPER">Cut Copper</option>
    <option value="EXPOSED_CUT_COPPER">Exposed Cut Copper</option>
    <option value="WEATHERED_CUT_COPPER">Weathered Cut Copper</option>
    <option value="OXIDIZED_CUT_COPPER">Oxidized Cut Copper</option>
    <option value="CUT_COPPER_STAIRS">Cut Copper Stairs</option>
    <option value="EXPOSED_CUT_COPPER_STAIRS">Exposed Cut Copper Stairs</option>
    <option value="WEATHERED_CUT_COPPER_STAIRS">Weathered Cut Copper Stairs</option>
    <option value="OXIDIZED_CUT_COPPER_STAIRS">Oxidized Cut Copper Stairs</option>
    <option value="CUT_COPPER_SLAB">Cut Copper Slab</option>
    <option value="EXPOSED_CUT_COPPER_SLAB">Exposed Cut Copper Slab</option>
    <option value="WEATHERED_CUT_COPPER_SLAB">Weathered Cut Copper Slab</option>
    <option value="OXIDIZED_CUT_COPPER_SLAB">Oxidized Cut Copper Slab</option>
    <option value="WAXED_COPPER_BLOCK">Waxed Copper Block</option>
    <option value="WAXED_EXPOSED_COPPER">Waxed Exposed Copper</option>
    <option value="WAXED_WEATHERED_COPPER">Waxed Weathered Copper</option>
    <option value="WAXED_OXIDIZED_COPPER">Waxed Oxidized Copper</option>
    <option value="WAXED_CUT_COPPER">Waxed Cut Copper</option>
    <option value="WAXED_EXPOSED_CUT_COPPER">Waxed Exposed Cut Copper</option>
    <option value="WAXED_WEATHERED_CUT_COPPER">Waxed Weathered Cut Copper</option>
    <option value="WAXED_OXIDIZED_CUT_COPPER">Waxed Oxidized Cut Copper</option>
    <option value="WAXED_CUT_COPPER_STAIRS">Waxed Cut Copper Stairs</option>
    <option value="WAXED_EXPOSED_CUT_COPPER_STAIRS">Waxed Exposed Cut Copper Stairs</option>
    <option value="WAXED_WEATHERED_CUT_COPPER_STAIRS">Waxed Weathered Cut Copper Stairs</option>
    <option value="WAXED_OXIDIZED_CUT_COPPER_STAIRS">Waxed Oxidized Cut Copper Stairs</option>
    <option value="WAXED_CUT_COPPER_SLAB">Waxed Cut Copper Slab</option>
    <option value="WAXED_EXPOSED_CUT_COPPER_SLAB">Waxed Exposed Cut Copper Slab</option>
    <option value="WAXED_WEATHERED_CUT_COPPER_SLAB">Waxed Weathered Cut Copper Slab</option>
    <option value="WAXED_OXIDIZED_CUT_COPPER_SLAB">Waxed Oxidized Cut Copper Slab</option>
    <option value="OAK_LOG">Oak Log</option>
    <option value="SPRUCE_LOG">Spruce Log</option>
    <option value="BIRCH_LOG">Birch Log</option>
    <option value="JUNGLE_LOG">Jungle Log</option>
    <option value="ACACIA_LOG">Acacia Log</option>
    <option value="DARK_OAK_LOG">Dark Oak Log</option>
    <option value="MANGROVE_LOG">Mangrove Log</option>
    <option value="MANGROVE_ROOTS">Mangrove Roots</option>
    <option value="MUDDY_MANGROVE_ROOTS">Muddy Mangrove Roots</option>
    <option value="CRIMSON_STEM">Crimson Stem</option>
    <option value="WARPED_STEM">Warped Stem</option>
    <option value="STRIPPED_OAK_LOG">Stripped Oak Log</option>
    <option value="STRIPPED_SPRUCE_LOG">Stripped Spruce Log</option>
    <option value="STRIPPED_BIRCH_LOG">Stripped Birch Log</option>
    <option value="STRIPPED_JUNGLE_LOG">Stripped Jungle Log</option>
    <option value="STRIPPED_ACACIA_LOG">Stripped Acacia Log</option>
    <option value="STRIPPED_DARK_OAK_LOG">Stripped Dark Oak Log</option>
    <option value="STRIPPED_MANGROVE_LOG">Stripped Mangrove Log</option>
    <option value="STRIPPED_CRIMSON_STEM">Stripped Crimson Stem</option>
    <option value="STRIPPED_WARPED_STEM">Stripped Warped Stem</option>
    <option value="STRIPPED_OAK_WOOD">Stripped Oak Wood</option>
    <option value="STRIPPED_SPRUCE_WOOD">Stripped Spruce Wood</option>
    <option value="STRIPPED_BIRCH_WOOD">Stripped Birch Wood</option>
    <option value="STRIPPED_JUNGLE_WOOD">Stripped Jungle Wood</option>
    <option value="STRIPPED_ACACIA_WOOD">Stripped Acacia Wood</option>
    <option value="STRIPPED_DARK_OAK_WOOD">Stripped Dark Oak Wood</option>
    <option value="STRIPPED_MANGROVE_WOOD">Stripped Mangrove Wood</option>
    <option value="STRIPPED_CRIMSON_HYPHAE">Stripped Crimson Hyphae</option>
    <option value="STRIPPED_WARPED_HYPHAE">Stripped Warped Hyphae</option>
    <option value="OAK_WOOD">Oak Wood</option>
    <option value="SPRUCE_WOOD">Spruce Wood</option>
    <option value="BIRCH_WOOD">Birch Wood</option>
    <option value="JUNGLE_WOOD">Jungle Wood</option>
    <option value="ACACIA_WOOD">Acacia Wood</option>
    <option value="DARK_OAK_WOOD">Dark Oak Wood</option>
    <option value="MANGROVE_WOOD">Mangrove Wood</option>
    <option value="CRIMSON_HYPHAE">Crimson Hyphae</option>
    <option value="WARPED_HYPHAE">Warped Hyphae</option>
    <option value="OAK_LEAVES">Oak Leaves</option>
    <option value="SPRUCE_LEAVES">Spruce Leaves</option>
    <option value="BIRCH_LEAVES">Birch Leaves</option>
    <option value="JUNGLE_LEAVES">Jungle Leaves</option>
    <option value="ACACIA_LEAVES">Acacia Leaves</option>
    <option value="DARK_OAK_LEAVES">Dark Oak Leaves</option>
    <option value="MANGROVE_LEAVES">Mangrove Leaves</option>
    <option value="AZALEA_LEAVES">Azalea Leaves</option>
    <option value="FLOWERING_AZALEA_LEAVES">Flowering Azalea Leaves</option>
    <option value="SPONGE">Sponge</option>
    <option value="WET_SPONGE">Wet Sponge</option>
    <option value="GLASS">Glass</option>
    <option value="TINTED_GLASS">Tinted Glass</option>
    <option value="LAPIS_BLOCK">Lapis Block</option>
    <option value="SANDSTONE">Sandstone</option>
    <option value="CHISELED_SANDSTONE">Chiseled Sandstone</option>
    <option value="CUT_SANDSTONE">Cut Sandstone</option>
    <option value="COBWEB">Cobweb</option>
    <option value="GRASS">Grass</option>
    <option value="FERN">Fern</option>
    <option value="AZALEA">Azalea</option>
    <option value="FLOWERING_AZALEA">Flowering Azalea</option>
    <option value="DEAD_BUSH">Dead Bush</option>
    <option value="SEAGRASS">Seagrass</option>
    <option value="SEA_PICKLE">Sea Pickle</option>
    <option value="WHITE_WOOL">White Wool</option>
    <option value="ORANGE_WOOL">Orange Wool</option>
    <option value="MAGENTA_WOOL">Magenta Wool</option>
    <option value="LIGHT_BLUE_WOOL">Light Blue Wool</option>
    <option value="YELLOW_WOOL">Yellow Wool</option>
    <option value="LIME_WOOL">Lime Wool</option>
    <option value="PINK_WOOL">Pink Wool</option>
    <option value="GRAY_WOOL">Gray Wool</option>
    <option value="LIGHT_GRAY_WOOL">Light Gray Wool</option>
    <option value="CYAN_WOOL">Cyan Wool</option>
    <option value="PURPLE_WOOL">Purple Wool</option>
    <option value="BLUE_WOOL">Blue Wool</option>
    <option value="BROWN_WOOL">Brown Wool</option>
    <option value="GREEN_WOOL">Green Wool</option>
    <option value="RED_WOOL">Red Wool</option>
    <option value="BLACK_WOOL">Black Wool</option>
    <option value="DANDELION">Dandelion</option>
    <option value="POPPY">Poppy</option>
    <option value="BLUE_ORCHID">Blue Orchid</option>
    <option value="ALLIUM">Allium</option>
    <option value="AZURE_BLUET">Azure Bluet</option>
    <option value="RED_TULIP">Red Tulip</option>
    <option value="ORANGE_TULIP">Orange Tulip</option>
    <option value="WHITE_TULIP">White Tulip</option>
    <option value="PINK_TULIP">Pink Tulip</option>
    <option value="OXEYE_DAISY">Oxeye Daisy</option>
    <option value="CORNFLOWER">Cornflower</option>
    <option value="LILY_OF_THE_VALLEY">Lily Of The Valley</option>
    <option value="WITHER_ROSE">Wither Rose</option>
    <option value="SPORE_BLOSSOM">Spore Blossom</option>
    <option value="BROWN_MUSHROOM">Brown Mushroom</option>
    <option value="RED_MUSHROOM">Red Mushroom</option>
    <option value="CRIMSON_FUNGUS">Crimson Fungus</option>
    <option value="WARPED_FUNGUS">Warped Fungus</option>
    <option value="CRIMSON_ROOTS">Crimson Roots</option>
    <option value="WARPED_ROOTS">Warped Roots</option>
    <option value="NETHER_SPROUTS">Nether Sprouts</option>
    <option value="WEEPING_VINES">Weeping Vines</option>
    <option value="TWISTING_VINES">Twisting Vines</option>
    <option value="SUGAR_CANE">Sugar Cane</option>
    <option value="KELP">Kelp</option>
    <option value="MOSS_CARPET">Moss Carpet</option>
    <option value="MOSS_BLOCK">Moss Block</option>
    <option value="HANGING_ROOTS">Hanging Roots</option>
    <option value="BIG_DRIPLEAF">Big Dripleaf</option>
    <option value="SMALL_DRIPLEAF">Small Dripleaf</option>
    <option value="BAMBOO">Bamboo</option>
    <option value="OAK_SLAB">Oak Slab</option>
    <option value="SPRUCE_SLAB">Spruce Slab</option>
    <option value="BIRCH_SLAB">Birch Slab</option>
    <option value="JUNGLE_SLAB">Jungle Slab</option>
    <option value="ACACIA_SLAB">Acacia Slab</option>
    <option value="DARK_OAK_SLAB">Dark Oak Slab</option>
    <option value="MANGROVE_SLAB">Mangrove Slab</option>
    <option value="CRIMSON_SLAB">Crimson Slab</option>
    <option value="WARPED_SLAB">Warped Slab</option>
    <option value="STONE_SLAB">Stone Slab</option>
    <option value="SMOOTH_STONE_SLAB">Smooth Stone Slab</option>
    <option value="SANDSTONE_SLAB">Sandstone Slab</option>
    <option value="CUT_SANDSTONE_SLAB">Cut Sandstone Slab</option>
    <option value="PETRIFIED_OAK_SLAB">Petrified Oak Slab</option>
    <option value="COBBLESTONE_SLAB">Cobblestone Slab</option>
    <option value="BRICK_SLAB">Brick Slab</option>
    <option value="STONE_BRICK_SLAB">Stone Brick Slab</option>
    <option value="MUD_BRICK_SLAB">Mud Brick Slab</option>
    <option value="NETHER_BRICK_SLAB">Nether Brick Slab</option>
    <option value="QUARTZ_SLAB">Quartz Slab</option>
    <option value="RED_SANDSTONE_SLAB">Red Sandstone Slab</option>
    <option value="CUT_RED_SANDSTONE_SLAB">Cut Red Sandstone Slab</option>
    <option value="PURPUR_SLAB">Purpur Slab</option>
    <option value="PRISMARINE_SLAB">Prismarine Slab</option>
    <option value="PRISMARINE_BRICK_SLAB">Prismarine Brick Slab</option>
    <option value="DARK_PRISMARINE_SLAB">Dark Prismarine Slab</option>
    <option value="SMOOTH_QUARTZ">Smooth Quartz</option>
    <option value="SMOOTH_RED_SANDSTONE">Smooth Red Sandstone</option>
    <option value="SMOOTH_SANDSTONE">Smooth Sandstone</option>
    <option value="SMOOTH_STONE">Smooth Stone</option>
    <option value="BRICKS">Bricks</option>
    <option value="BOOKSHELF">Bookshelf</option>
    <option value="MOSSY_COBBLESTONE">Mossy Cobblestone</option>
    <option value="OBSIDIAN">Obsidian</option>
    <option value="TORCH">Torch</option>
    <option value="END_ROD">End Rod</option>
    <option value="CHORUS_PLANT">Chorus Plant</option>
    <option value="CHORUS_FLOWER">Chorus Flower</option>
    <option value="PURPUR_BLOCK">Purpur Block</option>
    <option value="PURPUR_PILLAR">Purpur Pillar</option>
    <option value="PURPUR_STAIRS">Purpur Stairs</option>
    <option value="SPAWNER">Spawner</option>
    <option value="CHEST">Chest</option>
    <option value="CRAFTING_TABLE">Crafting Table</option>
    <option value="FARMLAND">Farmland</option>
    <option value="FURNACE">Furnace</option>
    <option value="LADDER">Ladder</option>
    <option value="COBBLESTONE_STAIRS">Cobblestone Stairs</option>
    <option value="SNOW">Snow</option>
    <option value="ICE">Ice</option>
    <option value="SNOW_BLOCK">Snow Block</option>
    <option value="CACTUS">Cactus</option>
    <option value="CLAY">Clay</option>
    <option value="JUKEBOX">Jukebox</option>
    <option value="OAK_FENCE">Oak Fence</option>
    <option value="SPRUCE_FENCE">Spruce Fence</option>
    <option value="BIRCH_FENCE">Birch Fence</option>
    <option value="JUNGLE_FENCE">Jungle Fence</option>
    <option value="ACACIA_FENCE">Acacia Fence</option>
    <option value="DARK_OAK_FENCE">Dark Oak Fence</option>
    <option value="MANGROVE_FENCE">Mangrove Fence</option>
    <option value="CRIMSON_FENCE">Crimson Fence</option>
    <option value="WARPED_FENCE">Warped Fence</option>
    <option value="PUMPKIN">Pumpkin</option>
    <option value="CARVED_PUMPKIN">Carved Pumpkin</option>
    <option value="JACK_O_LANTERN">Jack O Lantern</option>
    <option value="NETHERRACK">Netherrack</option>
    <option value="SOUL_SAND">Soul Sand</option>
    <option value="SOUL_SOIL">Soul Soil</option>
    <option value="BASALT">Basalt</option>
    <option value="POLISHED_BASALT">Polished Basalt</option>
    <option value="SMOOTH_BASALT">Smooth Basalt</option>
    <option value="SOUL_TORCH">Soul Torch</option>
    <option value="GLOWSTONE">Glowstone</option>
    <option value="INFESTED_STONE">Infested Stone</option>
    <option value="INFESTED_COBBLESTONE">Infested Cobblestone</option>
    <option value="INFESTED_STONE_BRICKS">Infested Stone Bricks</option>
    <option value="INFESTED_MOSSY_STONE_BRICKS">Infested Mossy Stone Bricks</option>
    <option value="INFESTED_CRACKED_STONE_BRICKS">Infested Cracked Stone Bricks</option>
    <option value="INFESTED_CHISELED_STONE_BRICKS">Infested Chiseled Stone Bricks</option>
    <option value="INFESTED_DEEPSLATE">Infested Deepslate</option>
    <option value="STONE_BRICKS">Stone Bricks</option>
    <option value="MOSSY_STONE_BRICKS">Mossy Stone Bricks</option>
    <option value="CRACKED_STONE_BRICKS">Cracked Stone Bricks</option>
    <option value="CHISELED_STONE_BRICKS">Chiseled Stone Bricks</option>
    <option value="PACKED_MUD">Packed Mud</option>
    <option value="MUD_BRICKS">Mud Bricks</option>
    <option value="DEEPSLATE_BRICKS">Deepslate Bricks</option>
    <option value="CRACKED_DEEPSLATE_BRICKS">Cracked Deepslate Bricks</option>
    <option value="DEEPSLATE_TILES">Deepslate Tiles</option>
    <option value="CRACKED_DEEPSLATE_TILES">Cracked Deepslate Tiles</option>
    <option value="CHISELED_DEEPSLATE">Chiseled Deepslate</option>
    <option value="REINFORCED_DEEPSLATE">Reinforced Deepslate</option>
    <option value="BROWN_MUSHROOM_BLOCK">Brown Mushroom Block</option>
    <option value="RED_MUSHROOM_BLOCK">Red Mushroom Block</option>
    <option value="MUSHROOM_STEM">Mushroom Stem</option>
    <option value="IRON_BARS">Iron Bars</option>
    <option value="CHAIN">Chain</option>
    <option value="GLASS_PANE">Glass Pane</option>
    <option value="MELON">Melon</option>
    <option value="VINE">Vine</option>
    <option value="GLOW_LICHEN">Glow Lichen</option>
    <option value="BRICK_STAIRS">Brick Stairs</option>
    <option value="STONE_BRICK_STAIRS">Stone Brick Stairs</option>
    <option value="MUD_BRICK_STAIRS">Mud Brick Stairs</option>
    <option value="MYCELIUM">Mycelium</option>
    <option value="LILY_PAD">Lily Pad</option>
    <option value="NETHER_BRICKS">Nether Bricks</option>
    <option value="CRACKED_NETHER_BRICKS">Cracked Nether Bricks</option>
    <option value="CHISELED_NETHER_BRICKS">Chiseled Nether Bricks</option>
    <option value="NETHER_BRICK_FENCE">Nether Brick Fence</option>
    <option value="NETHER_BRICK_STAIRS">Nether Brick Stairs</option>
    <option value="SCULK">Sculk</option>
    <option value="SCULK_VEIN">Sculk Vein</option>
    <option value="SCULK_CATALYST">Sculk Catalyst</option>
    <option value="SCULK_SHRIEKER">Sculk Shrieker</option>
    <option value="ENCHANTING_TABLE">Enchanting Table</option>
    <option value="END_PORTAL_FRAME">End Portal Frame</option>
    <option value="END_STONE">End Stone</option>
    <option value="END_STONE_BRICKS">End Stone Bricks</option>
    <option value="DRAGON_EGG">Dragon Egg</option>
    <option value="SANDSTONE_STAIRS">Sandstone Stairs</option>
    <option value="ENDER_CHEST">Ender Chest</option>
    <option value="EMERALD_BLOCK">Emerald Block</option>
    <option value="OAK_STAIRS">Oak Stairs</option>
    <option value="SPRUCE_STAIRS">Spruce Stairs</option>
    <option value="BIRCH_STAIRS">Birch Stairs</option>
    <option value="JUNGLE_STAIRS">Jungle Stairs</option>
    <option value="ACACIA_STAIRS">Acacia Stairs</option>
    <option value="DARK_OAK_STAIRS">Dark Oak Stairs</option>
    <option value="MANGROVE_STAIRS">Mangrove Stairs</option>
    <option value="CRIMSON_STAIRS">Crimson Stairs</option>
    <option value="WARPED_STAIRS">Warped Stairs</option>
    <option value="COMMAND_BLOCK">Command Block</option>
    <option value="BEACON">Beacon</option>
    <option value="COBBLESTONE_WALL">Cobblestone Wall</option>
    <option value="MOSSY_COBBLESTONE_WALL">Mossy Cobblestone Wall</option>
    <option value="BRICK_WALL">Brick Wall</option>
    <option value="PRISMARINE_WALL">Prismarine Wall</option>
    <option value="RED_SANDSTONE_WALL">Red Sandstone Wall</option>
    <option value="MOSSY_STONE_BRICK_WALL">Mossy Stone Brick Wall</option>
    <option value="GRANITE_WALL">Granite Wall</option>
    <option value="STONE_BRICK_WALL">Stone Brick Wall</option>
    <option value="MUD_BRICK_WALL">Mud Brick Wall</option>
    <option value="NETHER_BRICK_WALL">Nether Brick Wall</option>
    <option value="ANDESITE_WALL">Andesite Wall</option>
    <option value="RED_NETHER_BRICK_WALL">Red Nether Brick Wall</option>
    <option value="SANDSTONE_WALL">Sandstone Wall</option>
    <option value="END_STONE_BRICK_WALL">End Stone Brick Wall</option>
    <option value="DIORITE_WALL">Diorite Wall</option>
    <option value="BLACKSTONE_WALL">Blackstone Wall</option>
    <option value="POLISHED_BLACKSTONE_WALL">Polished Blackstone Wall</option>
    <option value="POLISHED_BLACKSTONE_BRICK_WALL">Polished Blackstone Brick Wall</option>
    <option value="COBBLED_DEEPSLATE_WALL">Cobbled Deepslate Wall</option>
    <option value="POLISHED_DEEPSLATE_WALL">Polished Deepslate Wall</option>
    <option value="DEEPSLATE_BRICK_WALL">Deepslate Brick Wall</option>
    <option value="DEEPSLATE_TILE_WALL">Deepslate Tile Wall</option>
    <option value="ANVIL">Anvil</option>
    <option value="CHIPPED_ANVIL">Chipped Anvil</option>
    <option value="DAMAGED_ANVIL">Damaged Anvil</option>
    <option value="CHISELED_QUARTZ_BLOCK">Chiseled Quartz Block</option>
    <option value="QUARTZ_BLOCK">Quartz Block</option>
    <option value="QUARTZ_BRICKS">Quartz Bricks</option>
    <option value="QUARTZ_PILLAR">Quartz Pillar</option>
    <option value="QUARTZ_STAIRS">Quartz Stairs</option>
    <option value="WHITE_TERRACOTTA">White Terracotta</option>
    <option value="ORANGE_TERRACOTTA">Orange Terracotta</option>
    <option value="MAGENTA_TERRACOTTA">Magenta Terracotta</option>
    <option value="LIGHT_BLUE_TERRACOTTA">Light Blue Terracotta</option>
    <option value="YELLOW_TERRACOTTA">Yellow Terracotta</option>
    <option value="LIME_TERRACOTTA">Lime Terracotta</option>
    <option value="PINK_TERRACOTTA">Pink Terracotta</option>
    <option value="GRAY_TERRACOTTA">Gray Terracotta</option>
    <option value="LIGHT_GRAY_TERRACOTTA">Light Gray Terracotta</option>
    <option value="CYAN_TERRACOTTA">Cyan Terracotta</option>
    <option value="PURPLE_TERRACOTTA">Purple Terracotta</option>
    <option value="BLUE_TERRACOTTA">Blue Terracotta</option>
    <option value="BROWN_TERRACOTTA">Brown Terracotta</option>
    <option value="GREEN_TERRACOTTA">Green Terracotta</option>
    <option value="RED_TERRACOTTA">Red Terracotta</option>
    <option value="BLACK_TERRACOTTA">Black Terracotta</option>
    <option value="BARRIER">Barrier</option>
    <option value="LIGHT">Light</option>
    <option value="HAY_BLOCK">Hay Block</option>
    <option value="WHITE_CARPET">White Carpet</option>
    <option value="ORANGE_CARPET">Orange Carpet</option>
    <option value="MAGENTA_CARPET">Magenta Carpet</option>
    <option value="LIGHT_BLUE_CARPET">Light Blue Carpet</option>
    <option value="YELLOW_CARPET">Yellow Carpet</option>
    <option value="LIME_CARPET">Lime Carpet</option>
    <option value="PINK_CARPET">Pink Carpet</option>
    <option value="GRAY_CARPET">Gray Carpet</option>
    <option value="LIGHT_GRAY_CARPET">Light Gray Carpet</option>
    <option value="CYAN_CARPET">Cyan Carpet</option>
    <option value="PURPLE_CARPET">Purple Carpet</option>
    <option value="BLUE_CARPET">Blue Carpet</option>
    <option value="BROWN_CARPET">Brown Carpet</option>
    <option value="GREEN_CARPET">Green Carpet</option>
    <option value="RED_CARPET">Red Carpet</option>
    <option value="BLACK_CARPET">Black Carpet</option>
    <option value="TERRACOTTA">Terracotta</option>
    <option value="PACKED_ICE">Packed Ice</option>
    <option value="DIRT_PATH">Dirt Path</option>
    <option value="SUNFLOWER">Sunflower</option>
    <option value="LILAC">Lilac</option>
    <option value="ROSE_BUSH">Rose Bush</option>
    <option value="PEONY">Peony</option>
    <option value="TALL_GRASS">Tall Grass</option>
    <option value="LARGE_FERN">Large Fern</option>
    <option value="WHITE_STAINED_GLASS">White Stained Glass</option>
    <option value="ORANGE_STAINED_GLASS">Orange Stained Glass</option>
    <option value="MAGENTA_STAINED_GLASS">Magenta Stained Glass</option>
    <option value="LIGHT_BLUE_STAINED_GLASS">Light Blue Stained Glass</option>
    <option value="YELLOW_STAINED_GLASS">Yellow Stained Glass</option>
    <option value="LIME_STAINED_GLASS">Lime Stained Glass</option>
    <option value="PINK_STAINED_GLASS">Pink Stained Glass</option>
    <option value="GRAY_STAINED_GLASS">Gray Stained Glass</option>
    <option value="LIGHT_GRAY_STAINED_GLASS">Light Gray Stained Glass</option>
    <option value="CYAN_STAINED_GLASS">Cyan Stained Glass</option>
    <option value="PURPLE_STAINED_GLASS">Purple Stained Glass</option>
    <option value="BLUE_STAINED_GLASS">Blue Stained Glass</option>
    <option value="BROWN_STAINED_GLASS">Brown Stained Glass</option>
    <option value="GREEN_STAINED_GLASS">Green Stained Glass</option>
    <option value="RED_STAINED_GLASS">Red Stained Glass</option>
    <option value="BLACK_STAINED_GLASS">Black Stained Glass</option>
    <option value="WHITE_STAINED_GLASS_PANE">White Stained Glass Pane</option>
    <option value="ORANGE_STAINED_GLASS_PANE">Orange Stained Glass Pane</option>
    <option value="MAGENTA_STAINED_GLASS_PANE">Magenta Stained Glass Pane</option>
    <option value="LIGHT_BLUE_STAINED_GLASS_PANE">Light Blue Stained Glass Pane</option>
    <option value="YELLOW_STAINED_GLASS_PANE">Yellow Stained Glass Pane</option>
    <option value="LIME_STAINED_GLASS_PANE">Lime Stained Glass Pane</option>
    <option value="PINK_STAINED_GLASS_PANE">Pink Stained Glass Pane</option>
    <option value="GRAY_STAINED_GLASS_PANE">Gray Stained Glass Pane</option>
    <option value="LIGHT_GRAY_STAINED_GLASS_PANE">Light Gray Stained Glass Pane</option>
    <option value="CYAN_STAINED_GLASS_PANE">Cyan Stained Glass Pane</option>
    <option value="PURPLE_STAINED_GLASS_PANE">Purple Stained Glass Pane</option>
    <option value="BLUE_STAINED_GLASS_PANE">Blue Stained Glass Pane</option>
    <option value="BROWN_STAINED_GLASS_PANE">Brown Stained Glass Pane</option>
    <option value="GREEN_STAINED_GLASS_PANE">Green Stained Glass Pane</option>
    <option value="RED_STAINED_GLASS_PANE">Red Stained Glass Pane</option>
    <option value="BLACK_STAINED_GLASS_PANE">Black Stained Glass Pane</option>
    <option value="PRISMARINE">Prismarine</option>
    <option value="PRISMARINE_BRICKS">Prismarine Bricks</option>
    <option value="DARK_PRISMARINE">Dark Prismarine</option>
    <option value="PRISMARINE_STAIRS">Prismarine Stairs</option>
    <option value="PRISMARINE_BRICK_STAIRS">Prismarine Brick Stairs</option>
    <option value="DARK_PRISMARINE_STAIRS">Dark Prismarine Stairs</option>
    <option value="SEA_LANTERN">Sea Lantern</option>
    <option value="RED_SANDSTONE">Red Sandstone</option>
    <option value="CHISELED_RED_SANDSTONE">Chiseled Red Sandstone</option>
    <option value="CUT_RED_SANDSTONE">Cut Red Sandstone</option>
    <option value="RED_SANDSTONE_STAIRS">Red Sandstone Stairs</option>
    <option value="REPEATING_COMMAND_BLOCK">Repeating Command Block</option>
    <option value="CHAIN_COMMAND_BLOCK">Chain Command Block</option>
    <option value="MAGMA_BLOCK">Magma Block</option>
    <option value="NETHER_WART_BLOCK">Nether Wart Block</option>
    <option value="WARPED_WART_BLOCK">Warped Wart Block</option>
    <option value="RED_NETHER_BRICKS">Red Nether Bricks</option>
    <option value="BONE_BLOCK">Bone Block</option>
    <option value="STRUCTURE_VOID">Structure Void</option>
    <option value="SHULKER_BOX">Shulker Box</option>
    <option value="WHITE_SHULKER_BOX">White Shulker Box</option>
    <option value="ORANGE_SHULKER_BOX">Orange Shulker Box</option>
    <option value="MAGENTA_SHULKER_BOX">Magenta Shulker Box</option>
    <option value="LIGHT_BLUE_SHULKER_BOX">Light Blue Shulker Box</option>
    <option value="YELLOW_SHULKER_BOX">Yellow Shulker Box</option>
    <option value="LIME_SHULKER_BOX">Lime Shulker Box</option>
    <option value="PINK_SHULKER_BOX">Pink Shulker Box</option>
    <option value="GRAY_SHULKER_BOX">Gray Shulker Box</option>
    <option value="LIGHT_GRAY_SHULKER_BOX">Light Gray Shulker Box</option>
    <option value="CYAN_SHULKER_BOX">Cyan Shulker Box</option>
    <option value="PURPLE_SHULKER_BOX">Purple Shulker Box</option>
    <option value="BLUE_SHULKER_BOX">Blue Shulker Box</option>
    <option value="BROWN_SHULKER_BOX">Brown Shulker Box</option>
    <option value="GREEN_SHULKER_BOX">Green Shulker Box</option>
    <option value="RED_SHULKER_BOX">Red Shulker Box</option>
    <option value="BLACK_SHULKER_BOX">Black Shulker Box</option>
    <option value="WHITE_GLAZED_TERRACOTTA">White Glazed Terracotta</option>
    <option value="ORANGE_GLAZED_TERRACOTTA">Orange Glazed Terracotta</option>
    <option value="MAGENTA_GLAZED_TERRACOTTA">Magenta Glazed Terracotta</option>
    <option value="LIGHT_BLUE_GLAZED_TERRACOTTA">Light Blue Glazed Terracotta</option>
    <option value="YELLOW_GLAZED_TERRACOTTA">Yellow Glazed Terracotta</option>
    <option value="LIME_GLAZED_TERRACOTTA">Lime Glazed Terracotta</option>
    <option value="PINK_GLAZED_TERRACOTTA">Pink Glazed Terracotta</option>
    <option value="GRAY_GLAZED_TERRACOTTA">Gray Glazed Terracotta</option>
    <option value="LIGHT_GRAY_GLAZED_TERRACOTTA">Light Gray Glazed Terracotta</option>
    <option value="CYAN_GLAZED_TERRACOTTA">Cyan Glazed Terracotta</option>
    <option value="PURPLE_GLAZED_TERRACOTTA">Purple Glazed Terracotta</option>
    <option value="BLUE_GLAZED_TERRACOTTA">Blue Glazed Terracotta</option>
    <option value="BROWN_GLAZED_TERRACOTTA">Brown Glazed Terracotta</option>
    <option value="GREEN_GLAZED_TERRACOTTA">Green Glazed Terracotta</option>
    <option value="RED_GLAZED_TERRACOTTA">Red Glazed Terracotta</option>
    <option value="BLACK_GLAZED_TERRACOTTA">Black Glazed Terracotta</option>
    <option value="WHITE_CONCRETE">White Concrete</option>
    <option value="ORANGE_CONCRETE">Orange Concrete</option>
    <option value="MAGENTA_CONCRETE">Magenta Concrete</option>
    <option value="LIGHT_BLUE_CONCRETE">Light Blue Concrete</option>
    <option value="YELLOW_CONCRETE">Yellow Concrete</option>
    <option value="LIME_CONCRETE">Lime Concrete</option>
    <option value="PINK_CONCRETE">Pink Concrete</option>
    <option value="GRAY_CONCRETE">Gray Concrete</option>
    <option value="LIGHT_GRAY_CONCRETE">Light Gray Concrete</option>
    <option value="CYAN_CONCRETE">Cyan Concrete</option>
    <option value="PURPLE_CONCRETE">Purple Concrete</option>
    <option value="BLUE_CONCRETE">Blue Concrete</option>
    <option value="BROWN_CONCRETE">Brown Concrete</option>
    <option value="GREEN_CONCRETE">Green Concrete</option>
    <option value="RED_CONCRETE">Red Concrete</option>
    <option value="BLACK_CONCRETE">Black Concrete</option>
    <option value="WHITE_CONCRETE_POWDER">White Concrete Powder</option>
    <option value="ORANGE_CONCRETE_POWDER">Orange Concrete Powder</option>
    <option value="MAGENTA_CONCRETE_POWDER">Magenta Concrete Powder</option>
    <option value="LIGHT_BLUE_CONCRETE_POWDER">Light Blue Concrete Powder</option>
    <option value="YELLOW_CONCRETE_POWDER">Yellow Concrete Powder</option>
    <option value="LIME_CONCRETE_POWDER">Lime Concrete Powder</option>
    <option value="PINK_CONCRETE_POWDER">Pink Concrete Powder</option>
    <option value="GRAY_CONCRETE_POWDER">Gray Concrete Powder</option>
    <option value="LIGHT_GRAY_CONCRETE_POWDER">Light Gray Concrete Powder</option>
    <option value="CYAN_CONCRETE_POWDER">Cyan Concrete Powder</option>
    <option value="PURPLE_CONCRETE_POWDER">Purple Concrete Powder</option>
    <option value="BLUE_CONCRETE_POWDER">Blue Concrete Powder</option>
    <option value="BROWN_CONCRETE_POWDER">Brown Concrete Powder</option>
    <option value="GREEN_CONCRETE_POWDER">Green Concrete Powder</option>
    <option value="RED_CONCRETE_POWDER">Red Concrete Powder</option>
    <option value="BLACK_CONCRETE_POWDER">Black Concrete Powder</option>
    <option value="TURTLE_EGG">Turtle Egg</option>
    <option value="DEAD_TUBE_CORAL_BLOCK">Dead Tube Coral Block</option>
    <option value="DEAD_BRAIN_CORAL_BLOCK">Dead Brain Coral Block</option>
    <option value="DEAD_BUBBLE_CORAL_BLOCK">Dead Bubble Coral Block</option>
    <option value="DEAD_FIRE_CORAL_BLOCK">Dead Fire Coral Block</option>
    <option value="DEAD_HORN_CORAL_BLOCK">Dead Horn Coral Block</option>
    <option value="TUBE_CORAL_BLOCK">Tube Coral Block</option>
    <option value="BRAIN_CORAL_BLOCK">Brain Coral Block</option>
    <option value="BUBBLE_CORAL_BLOCK">Bubble Coral Block</option>
    <option value="FIRE_CORAL_BLOCK">Fire Coral Block</option>
    <option value="HORN_CORAL_BLOCK">Horn Coral Block</option>
    <option value="TUBE_CORAL">Tube Coral</option>
    <option value="BRAIN_CORAL">Brain Coral</option>
    <option value="BUBBLE_CORAL">Bubble Coral</option>
    <option value="FIRE_CORAL">Fire Coral</option>
    <option value="HORN_CORAL">Horn Coral</option>
    <option value="DEAD_BRAIN_CORAL">Dead Brain Coral</option>
    <option value="DEAD_BUBBLE_CORAL">Dead Bubble Coral</option>
    <option value="DEAD_FIRE_CORAL">Dead Fire Coral</option>
    <option value="DEAD_HORN_CORAL">Dead Horn Coral</option>
    <option value="DEAD_TUBE_CORAL">Dead Tube Coral</option>
    <option value="TUBE_CORAL_FAN">Tube Coral Fan</option>
    <option value="BRAIN_CORAL_FAN">Brain Coral Fan</option>
    <option value="BUBBLE_CORAL_FAN">Bubble Coral Fan</option>
    <option value="FIRE_CORAL_FAN">Fire Coral Fan</option>
    <option value="HORN_CORAL_FAN">Horn Coral Fan</option>
    <option value="DEAD_TUBE_CORAL_FAN">Dead Tube Coral Fan</option>
    <option value="DEAD_BRAIN_CORAL_FAN">Dead Brain Coral Fan</option>
    <option value="DEAD_BUBBLE_CORAL_FAN">Dead Bubble Coral Fan</option>
    <option value="DEAD_FIRE_CORAL_FAN">Dead Fire Coral Fan</option>
    <option value="DEAD_HORN_CORAL_FAN">Dead Horn Coral Fan</option>
    <option value="BLUE_ICE">Blue Ice</option>
    <option value="CONDUIT">Conduit</option>
    <option value="POLISHED_GRANITE_STAIRS">Polished Granite Stairs</option>
    <option value="SMOOTH_RED_SANDSTONE_STAIRS">Smooth Red Sandstone Stairs</option>
    <option value="MOSSY_STONE_BRICK_STAIRS">Mossy Stone Brick Stairs</option>
    <option value="POLISHED_DIORITE_STAIRS">Polished Diorite Stairs</option>
    <option value="MOSSY_COBBLESTONE_STAIRS">Mossy Cobblestone Stairs</option>
    <option value="END_STONE_BRICK_STAIRS">End Stone Brick Stairs</option>
    <option value="STONE_STAIRS">Stone Stairs</option>
    <option value="SMOOTH_SANDSTONE_STAIRS">Smooth Sandstone Stairs</option>
    <option value="SMOOTH_QUARTZ_STAIRS">Smooth Quartz Stairs</option>
    <option value="GRANITE_STAIRS">Granite Stairs</option>
    <option value="ANDESITE_STAIRS">Andesite Stairs</option>
    <option value="RED_NETHER_BRICK_STAIRS">Red Nether Brick Stairs</option>
    <option value="POLISHED_ANDESITE_STAIRS">Polished Andesite Stairs</option>
    <option value="DIORITE_STAIRS">Diorite Stairs</option>
    <option value="COBBLED_DEEPSLATE_STAIRS">Cobbled Deepslate Stairs</option>
    <option value="POLISHED_DEEPSLATE_STAIRS">Polished Deepslate Stairs</option>
    <option value="DEEPSLATE_BRICK_STAIRS">Deepslate Brick Stairs</option>
    <option value="DEEPSLATE_TILE_STAIRS">Deepslate Tile Stairs</option>
    <option value="POLISHED_GRANITE_SLAB">Polished Granite Slab</option>
    <option value="SMOOTH_RED_SANDSTONE_SLAB">Smooth Red Sandstone Slab</option>
    <option value="MOSSY_STONE_BRICK_SLAB">Mossy Stone Brick Slab</option>
    <option value="POLISHED_DIORITE_SLAB">Polished Diorite Slab</option>
    <option value="MOSSY_COBBLESTONE_SLAB">Mossy Cobblestone Slab</option>
    <option value="END_STONE_BRICK_SLAB">End Stone Brick Slab</option>
    <option value="SMOOTH_SANDSTONE_SLAB">Smooth Sandstone Slab</option>
    <option value="SMOOTH_QUARTZ_SLAB">Smooth Quartz Slab</option>
    <option value="GRANITE_SLAB">Granite Slab</option>
    <option value="ANDESITE_SLAB">Andesite Slab</option>
    <option value="RED_NETHER_BRICK_SLAB">Red Nether Brick Slab</option>
    <option value="POLISHED_ANDESITE_SLAB">Polished Andesite Slab</option>
    <option value="DIORITE_SLAB">Diorite Slab</option>
    <option value="COBBLED_DEEPSLATE_SLAB">Cobbled Deepslate Slab</option>
    <option value="POLISHED_DEEPSLATE_SLAB">Polished Deepslate Slab</option>
    <option value="DEEPSLATE_BRICK_SLAB">Deepslate Brick Slab</option>
    <option value="DEEPSLATE_TILE_SLAB">Deepslate Tile Slab</option>
    <option value="SCAFFOLDING">Scaffolding</option>
    <option value="REDSTONE">Redstone</option>
    <option value="REDSTONE_TORCH">Redstone Torch</option>
    <option value="REDSTONE_BLOCK">Redstone Block</option>
    <option value="REPEATER">Repeater</option>
    <option value="COMPARATOR">Comparator</option>
    <option value="PISTON">Piston</option>
    <option value="STICKY_PISTON">Sticky Piston</option>
    <option value="SLIME_BLOCK">Slime Block</option>
    <option value="HONEY_BLOCK">Honey Block</option>
    <option value="OBSERVER">Observer</option>
    <option value="HOPPER">Hopper</option>
    <option value="DISPENSER">Dispenser</option>
    <option value="DROPPER">Dropper</option>
    <option value="LECTERN">Lectern</option>
    <option value="TARGET">Target</option>
    <option value="LEVER">Lever</option>
    <option value="LIGHTNING_ROD">Lightning Rod</option>
    <option value="DAYLIGHT_DETECTOR">Daylight Detector</option>
    <option value="SCULK_SENSOR">Sculk Sensor</option>
    <option value="TRIPWIRE_HOOK">Tripwire Hook</option>
    <option value="TRAPPED_CHEST">Trapped Chest</option>
    <option value="TNT">Tnt</option>
    <option value="REDSTONE_LAMP">Redstone Lamp</option>
    <option value="NOTE_BLOCK">Note Block</option>
    <option value="STONE_BUTTON">Stone Button</option>
    <option value="POLISHED_BLACKSTONE_BUTTON">Polished Blackstone Button</option>
    <option value="OAK_BUTTON">Oak Button</option>
    <option value="SPRUCE_BUTTON">Spruce Button</option>
    <option value="BIRCH_BUTTON">Birch Button</option>
    <option value="JUNGLE_BUTTON">Jungle Button</option>
    <option value="ACACIA_BUTTON">Acacia Button</option>
    <option value="DARK_OAK_BUTTON">Dark Oak Button</option>
    <option value="MANGROVE_BUTTON">Mangrove Button</option>
    <option value="CRIMSON_BUTTON">Crimson Button</option>
    <option value="WARPED_BUTTON">Warped Button</option>
    <option value="STONE_PRESSURE_PLATE">Stone Pressure Plate</option>
    <option value="POLISHED_BLACKSTONE_PRESSURE_PLATE">Polished Blackstone Pressure Plate</option>
    <option value="LIGHT_WEIGHTED_PRESSURE_PLATE">Light Weighted Pressure Plate</option>
    <option value="HEAVY_WEIGHTED_PRESSURE_PLATE">Heavy Weighted Pressure Plate</option>
    <option value="OAK_PRESSURE_PLATE">Oak Pressure Plate</option>
    <option value="SPRUCE_PRESSURE_PLATE">Spruce Pressure Plate</option>
    <option value="BIRCH_PRESSURE_PLATE">Birch Pressure Plate</option>
    <option value="JUNGLE_PRESSURE_PLATE">Jungle Pressure Plate</option>
    <option value="ACACIA_PRESSURE_PLATE">Acacia Pressure Plate</option>
    <option value="DARK_OAK_PRESSURE_PLATE">Dark Oak Pressure Plate</option>
    <option value="MANGROVE_PRESSURE_PLATE">Mangrove Pressure Plate</option>
    <option value="CRIMSON_PRESSURE_PLATE">Crimson Pressure Plate</option>
    <option value="WARPED_PRESSURE_PLATE">Warped Pressure Plate</option>
    <option value="IRON_DOOR">Iron Door</option>
    <option value="OAK_DOOR">Oak Door</option>
    <option value="SPRUCE_DOOR">Spruce Door</option>
    <option value="BIRCH_DOOR">Birch Door</option>
    <option value="JUNGLE_DOOR">Jungle Door</option>
    <option value="ACACIA_DOOR">Acacia Door</option>
    <option value="DARK_OAK_DOOR">Dark Oak Door</option>
    <option value="MANGROVE_DOOR">Mangrove Door</option>
    <option value="CRIMSON_DOOR">Crimson Door</option>
    <option value="WARPED_DOOR">Warped Door</option>
    <option value="IRON_TRAPDOOR">Iron Trapdoor</option>
    <option value="OAK_TRAPDOOR">Oak Trapdoor</option>
    <option value="SPRUCE_TRAPDOOR">Spruce Trapdoor</option>
    <option value="BIRCH_TRAPDOOR">Birch Trapdoor</option>
    <option value="JUNGLE_TRAPDOOR">Jungle Trapdoor</option>
    <option value="ACACIA_TRAPDOOR">Acacia Trapdoor</option>
    <option value="DARK_OAK_TRAPDOOR">Dark Oak Trapdoor</option>
    <option value="MANGROVE_TRAPDOOR">Mangrove Trapdoor</option>
    <option value="CRIMSON_TRAPDOOR">Crimson Trapdoor</option>
    <option value="WARPED_TRAPDOOR">Warped Trapdoor</option>
    <option value="OAK_FENCE_GATE">Oak Fence Gate</option>
    <option value="SPRUCE_FENCE_GATE">Spruce Fence Gate</option>
    <option value="BIRCH_FENCE_GATE">Birch Fence Gate</option>
    <option value="JUNGLE_FENCE_GATE">Jungle Fence Gate</option>
    <option value="ACACIA_FENCE_GATE">Acacia Fence Gate</option>
    <option value="DARK_OAK_FENCE_GATE">Dark Oak Fence Gate</option>
    <option value="MANGROVE_FENCE_GATE">Mangrove Fence Gate</option>
    <option value="CRIMSON_FENCE_GATE">Crimson Fence Gate</option>
    <option value="WARPED_FENCE_GATE">Warped Fence Gate</option>
    <option value="POWERED_RAIL">Powered Rail</option>
    <option value="DETECTOR_RAIL">Detector Rail</option>
    <option value="RAIL">Rail</option>
    <option value="ACTIVATOR_RAIL">Activator Rail</option>
    <option value="SADDLE">Saddle</option>
    <option value="MINECART">Minecart</option>
    <option value="CHEST_MINECART">Chest Minecart</option>
    <option value="FURNACE_MINECART">Furnace Minecart</option>
    <option value="TNT_MINECART">Tnt Minecart</option>
    <option value="HOPPER_MINECART">Hopper Minecart</option>
    <option value="CARROT_ON_A_STICK">Carrot On A Stick</option>
    <option value="WARPED_FUNGUS_ON_A_STICK">Warped Fungus On A Stick</option>
    <option value="ELYTRA">Elytra</option>
    <option value="OAK_BOAT">Oak Boat</option>
    <option value="OAK_CHEST_BOAT">Oak Chest Boat</option>
    <option value="SPRUCE_BOAT">Spruce Boat</option>
    <option value="SPRUCE_CHEST_BOAT">Spruce Chest Boat</option>
    <option value="BIRCH_BOAT">Birch Boat</option>
    <option value="BIRCH_CHEST_BOAT">Birch Chest Boat</option>
    <option value="JUNGLE_BOAT">Jungle Boat</option>
    <option value="JUNGLE_CHEST_BOAT">Jungle Chest Boat</option>
    <option value="ACACIA_BOAT">Acacia Boat</option>
    <option value="ACACIA_CHEST_BOAT">Acacia Chest Boat</option>
    <option value="DARK_OAK_BOAT">Dark Oak Boat</option>
    <option value="DARK_OAK_CHEST_BOAT">Dark Oak Chest Boat</option>
    <option value="MANGROVE_BOAT">Mangrove Boat</option>
    <option value="MANGROVE_CHEST_BOAT">Mangrove Chest Boat</option>
    <option value="STRUCTURE_BLOCK">Structure Block</option>
    <option value="JIGSAW">Jigsaw</option>
    <option value="TURTLE_HELMET">Turtle Helmet</option>
    <option value="SCUTE">Scute</option>
    <option value="FLINT_AND_STEEL">Flint And Steel</option>
    <option value="APPLE">Apple</option>
    <option value="BOW">Bow</option>
    <option value="ARROW">Arrow</option>
    <option value="COAL">Coal</option>
    <option value="CHARCOAL">Charcoal</option>
    <option value="DIAMOND">Diamond</option>
    <option value="EMERALD">Emerald</option>
    <option value="LAPIS_LAZULI">Lapis Lazuli</option>
    <option value="QUARTZ">Quartz</option>
    <option value="AMETHYST_SHARD">Amethyst Shard</option>
    <option value="RAW_IRON">Raw Iron</option>
    <option value="IRON_INGOT">Iron Ingot</option>
    <option value="RAW_COPPER">Raw Copper</option>
    <option value="COPPER_INGOT">Copper Ingot</option>
    <option value="RAW_GOLD">Raw Gold</option>
    <option value="GOLD_INGOT">Gold Ingot</option>
    <option value="NETHERITE_INGOT">Netherite Ingot</option>
    <option value="NETHERITE_SCRAP">Netherite Scrap</option>
    <option value="WOODEN_SWORD">Wooden Sword</option>
    <option value="WOODEN_SHOVEL">Wooden Shovel</option>
    <option value="WOODEN_PICKAXE">Wooden Pickaxe</option>
    <option value="WOODEN_AXE">Wooden Axe</option>
    <option value="WOODEN_HOE">Wooden Hoe</option>
    <option value="STONE_SWORD">Stone Sword</option>
    <option value="STONE_SHOVEL">Stone Shovel</option>
    <option value="STONE_PICKAXE">Stone Pickaxe</option>
    <option value="STONE_AXE">Stone Axe</option>
    <option value="STONE_HOE">Stone Hoe</option>
    <option value="GOLDEN_SWORD">Golden Sword</option>
    <option value="GOLDEN_SHOVEL">Golden Shovel</option>
    <option value="GOLDEN_PICKAXE">Golden Pickaxe</option>
    <option value="GOLDEN_AXE">Golden Axe</option>
    <option value="GOLDEN_HOE">Golden Hoe</option>
    <option value="IRON_SWORD">Iron Sword</option>
    <option value="IRON_SHOVEL">Iron Shovel</option>
    <option value="IRON_PICKAXE">Iron Pickaxe</option>
    <option value="IRON_AXE">Iron Axe</option>
    <option value="IRON_HOE">Iron Hoe</option>
    <option value="DIAMOND_SWORD">Diamond Sword</option>
    <option value="DIAMOND_SHOVEL">Diamond Shovel</option>
    <option value="DIAMOND_PICKAXE">Diamond Pickaxe</option>
    <option value="DIAMOND_AXE">Diamond Axe</option>
    <option value="DIAMOND_HOE">Diamond Hoe</option>
    <option value="NETHERITE_SWORD">Netherite Sword</option>
    <option value="NETHERITE_SHOVEL">Netherite Shovel</option>
    <option value="NETHERITE_PICKAXE">Netherite Pickaxe</option>
    <option value="NETHERITE_AXE">Netherite Axe</option>
    <option value="NETHERITE_HOE">Netherite Hoe</option>
    <option value="STICK">Stick</option>
    <option value="BOWL">Bowl</option>
    <option value="MUSHROOM_STEW">Mushroom Stew</option>
    <option value="STRING">String</option>
    <option value="FEATHER">Feather</option>
    <option value="GUNPOWDER">Gunpowder</option>
    <option value="WHEAT_SEEDS">Wheat Seeds</option>
    <option value="WHEAT">Wheat</option>
    <option value="BREAD">Bread</option>
    <option value="LEATHER_HELMET">Leather Helmet</option>
    <option value="LEATHER_CHESTPLATE">Leather Chestplate</option>
    <option value="LEATHER_LEGGINGS">Leather Leggings</option>
    <option value="LEATHER_BOOTS">Leather Boots</option>
    <option value="CHAINMAIL_HELMET">Chainmail Helmet</option>
    <option value="CHAINMAIL_CHESTPLATE">Chainmail Chestplate</option>
    <option value="CHAINMAIL_LEGGINGS">Chainmail Leggings</option>
    <option value="CHAINMAIL_BOOTS">Chainmail Boots</option>
    <option value="IRON_HELMET">Iron Helmet</option>
    <option value="IRON_CHESTPLATE">Iron Chestplate</option>
    <option value="IRON_LEGGINGS">Iron Leggings</option>
    <option value="IRON_BOOTS">Iron Boots</option>
    <option value="DIAMOND_HELMET">Diamond Helmet</option>
    <option value="DIAMOND_CHESTPLATE">Diamond Chestplate</option>
    <option value="DIAMOND_LEGGINGS">Diamond Leggings</option>
    <option value="DIAMOND_BOOTS">Diamond Boots</option>
    <option value="GOLDEN_HELMET">Golden Helmet</option>
    <option value="GOLDEN_CHESTPLATE">Golden Chestplate</option>
    <option value="GOLDEN_LEGGINGS">Golden Leggings</option>
    <option value="GOLDEN_BOOTS">Golden Boots</option>
    <option value="NETHERITE_HELMET">Netherite Helmet</option>
    <option value="NETHERITE_CHESTPLATE">Netherite Chestplate</option>
    <option value="NETHERITE_LEGGINGS">Netherite Leggings</option>
    <option value="NETHERITE_BOOTS">Netherite Boots</option>
    <option value="FLINT">Flint</option>
    <option value="PORKCHOP">Porkchop</option>
    <option value="COOKED_PORKCHOP">Cooked Porkchop</option>
    <option value="PAINTING">Painting</option>
    <option value="GOLDEN_APPLE">Golden Apple</option>
    <option value="ENCHANTED_GOLDEN_APPLE">Enchanted Golden Apple</option>
    <option value="OAK_SIGN">Oak Sign</option>
    <option value="SPRUCE_SIGN">Spruce Sign</option>
    <option value="BIRCH_SIGN">Birch Sign</option>
    <option value="JUNGLE_SIGN">Jungle Sign</option>
    <option value="ACACIA_SIGN">Acacia Sign</option>
    <option value="DARK_OAK_SIGN">Dark Oak Sign</option>
    <option value="MANGROVE_SIGN">Mangrove Sign</option>
    <option value="CRIMSON_SIGN">Crimson Sign</option>
    <option value="WARPED_SIGN">Warped Sign</option>
    <option value="BUCKET">Bucket</option>
    <option value="WATER_BUCKET">Water Bucket</option>
    <option value="LAVA_BUCKET">Lava Bucket</option>
    <option value="POWDER_SNOW_BUCKET">Powder Snow Bucket</option>
    <option value="SNOWBALL">Snowball</option>
    <option value="LEATHER">Leather</option>
    <option value="MILK_BUCKET">Milk Bucket</option>
    <option value="PUFFERFISH_BUCKET">Pufferfish Bucket</option>
    <option value="SALMON_BUCKET">Salmon Bucket</option>
    <option value="COD_BUCKET">Cod Bucket</option>
    <option value="TROPICAL_FISH_BUCKET">Tropical Fish Bucket</option>
    <option value="AXOLOTL_BUCKET">Axolotl Bucket</option>
    <option value="TADPOLE_BUCKET">Tadpole Bucket</option>
    <option value="BRICK">Brick</option>
    <option value="CLAY_BALL">Clay Ball</option>
    <option value="DRIED_KELP_BLOCK">Dried Kelp Block</option>
    <option value="PAPER">Paper</option>
    <option value="BOOK">Book</option>
    <option value="SLIME_BALL">Slime Ball</option>
    <option value="EGG">Egg</option>
    <option value="COMPASS">Compass</option>
    <option value="RECOVERY_COMPASS">Recovery Compass</option>
    <option value="BUNDLE">Bundle</option>
    <option value="FISHING_ROD">Fishing Rod</option>
    <option value="CLOCK">Clock</option>
    <option value="SPYGLASS">Spyglass</option>
    <option value="GLOWSTONE_DUST">Glowstone Dust</option>
    <option value="COD">Cod</option>
    <option value="SALMON">Salmon</option>
    <option value="TROPICAL_FISH">Tropical Fish</option>
    <option value="PUFFERFISH">Pufferfish</option>
    <option value="COOKED_COD">Cooked Cod</option>
    <option value="COOKED_SALMON">Cooked Salmon</option>
    <option value="INK_SAC">Ink Sac</option>
    <option value="GLOW_INK_SAC">Glow Ink Sac</option>
    <option value="COCOA_BEANS">Cocoa Beans</option>
    <option value="WHITE_DYE">White Dye</option>
    <option value="ORANGE_DYE">Orange Dye</option>
    <option value="MAGENTA_DYE">Magenta Dye</option>
    <option value="LIGHT_BLUE_DYE">Light Blue Dye</option>
    <option value="YELLOW_DYE">Yellow Dye</option>
    <option value="LIME_DYE">Lime Dye</option>
    <option value="PINK_DYE">Pink Dye</option>
    <option value="GRAY_DYE">Gray Dye</option>
    <option value="LIGHT_GRAY_DYE">Light Gray Dye</option>
    <option value="CYAN_DYE">Cyan Dye</option>
    <option value="PURPLE_DYE">Purple Dye</option>
    <option value="BLUE_DYE">Blue Dye</option>
    <option value="BROWN_DYE">Brown Dye</option>
    <option value="GREEN_DYE">Green Dye</option>
    <option value="RED_DYE">Red Dye</option>
    <option value="BLACK_DYE">Black Dye</option>
    <option value="BONE_MEAL">Bone Meal</option>
    <option value="BONE">Bone</option>
    <option value="SUGAR">Sugar</option>
    <option value="CAKE">Cake</option>
    <option value="WHITE_BED">White Bed</option>
    <option value="ORANGE_BED">Orange Bed</option>
    <option value="MAGENTA_BED">Magenta Bed</option>
    <option value="LIGHT_BLUE_BED">Light Blue Bed</option>
    <option value="YELLOW_BED">Yellow Bed</option>
    <option value="LIME_BED">Lime Bed</option>
    <option value="PINK_BED">Pink Bed</option>
    <option value="GRAY_BED">Gray Bed</option>
    <option value="LIGHT_GRAY_BED">Light Gray Bed</option>
    <option value="CYAN_BED">Cyan Bed</option>
    <option value="PURPLE_BED">Purple Bed</option>
    <option value="BLUE_BED">Blue Bed</option>
    <option value="BROWN_BED">Brown Bed</option>
    <option value="GREEN_BED">Green Bed</option>
    <option value="RED_BED">Red Bed</option>
    <option value="BLACK_BED">Black Bed</option>
    <option value="COOKIE">Cookie</option>
    <option value="FILLED_MAP">Filled Map</option>
    <option value="SHEARS">Shears</option>
    <option value="MELON_SLICE">Melon Slice</option>
    <option value="DRIED_KELP">Dried Kelp</option>
    <option value="PUMPKIN_SEEDS">Pumpkin Seeds</option>
    <option value="MELON_SEEDS">Melon Seeds</option>
    <option value="BEEF">Beef</option>
    <option value="COOKED_BEEF">Cooked Beef</option>
    <option value="CHICKEN">Chicken</option>
    <option value="COOKED_CHICKEN">Cooked Chicken</option>
    <option value="ROTTEN_FLESH">Rotten Flesh</option>
    <option value="ENDER_PEARL">Ender Pearl</option>
    <option value="BLAZE_ROD">Blaze Rod</option>
    <option value="GHAST_TEAR">Ghast Tear</option>
    <option value="GOLD_NUGGET">Gold Nugget</option>
    <option value="NETHER_WART">Nether Wart</option>
    <option value="POTION">Potion</option>
    <option value="GLASS_BOTTLE">Glass Bottle</option>
    <option value="SPIDER_EYE">Spider Eye</option>
    <option value="FERMENTED_SPIDER_EYE">Fermented Spider Eye</option>
    <option value="BLAZE_POWDER">Blaze Powder</option>
    <option value="MAGMA_CREAM">Magma Cream</option>
    <option value="BREWING_STAND">Brewing Stand</option>
    <option value="CAULDRON">Cauldron</option>
    <option value="ENDER_EYE">Ender Eye</option>
    <option value="GLISTERING_MELON_SLICE">Glistering Melon Slice</option>
    <option value="ALLAY_SPAWN_EGG">Allay Spawn Egg</option>
    <option value="AXOLOTL_SPAWN_EGG">Axolotl Spawn Egg</option>
    <option value="BAT_SPAWN_EGG">Bat Spawn Egg</option>
    <option value="BEE_SPAWN_EGG">Bee Spawn Egg</option>
    <option value="BLAZE_SPAWN_EGG">Blaze Spawn Egg</option>
    <option value="CAT_SPAWN_EGG">Cat Spawn Egg</option>
    <option value="CAVE_SPIDER_SPAWN_EGG">Cave Spider Spawn Egg</option>
    <option value="CHICKEN_SPAWN_EGG">Chicken Spawn Egg</option>
    <option value="COD_SPAWN_EGG">Cod Spawn Egg</option>
    <option value="COW_SPAWN_EGG">Cow Spawn Egg</option>
    <option value="CREEPER_SPAWN_EGG">Creeper Spawn Egg</option>
    <option value="DOLPHIN_SPAWN_EGG">Dolphin Spawn Egg</option>
    <option value="DONKEY_SPAWN_EGG">Donkey Spawn Egg</option>
    <option value="DROWNED_SPAWN_EGG">Drowned Spawn Egg</option>
    <option value="ELDER_GUARDIAN_SPAWN_EGG">Elder Guardian Spawn Egg</option>
    <option value="ENDERMAN_SPAWN_EGG">Enderman Spawn Egg</option>
    <option value="ENDERMITE_SPAWN_EGG">Endermite Spawn Egg</option>
    <option value="EVOKER_SPAWN_EGG">Evoker Spawn Egg</option>
    <option value="FOX_SPAWN_EGG">Fox Spawn Egg</option>
    <option value="FROG_SPAWN_EGG">Frog Spawn Egg</option>
    <option value="GHAST_SPAWN_EGG">Ghast Spawn Egg</option>
    <option value="GLOW_SQUID_SPAWN_EGG">Glow Squid Spawn Egg</option>
    <option value="GOAT_SPAWN_EGG">Goat Spawn Egg</option>
    <option value="GUARDIAN_SPAWN_EGG">Guardian Spawn Egg</option>
    <option value="HOGLIN_SPAWN_EGG">Hoglin Spawn Egg</option>
    <option value="HORSE_SPAWN_EGG">Horse Spawn Egg</option>
    <option value="HUSK_SPAWN_EGG">Husk Spawn Egg</option>
    <option value="LLAMA_SPAWN_EGG">Llama Spawn Egg</option>
    <option value="MAGMA_CUBE_SPAWN_EGG">Magma Cube Spawn Egg</option>
    <option value="MOOSHROOM_SPAWN_EGG">Mooshroom Spawn Egg</option>
    <option value="MULE_SPAWN_EGG">Mule Spawn Egg</option>
    <option value="OCELOT_SPAWN_EGG">Ocelot Spawn Egg</option>
    <option value="PANDA_SPAWN_EGG">Panda Spawn Egg</option>
    <option value="PARROT_SPAWN_EGG">Parrot Spawn Egg</option>
    <option value="PHANTOM_SPAWN_EGG">Phantom Spawn Egg</option>
    <option value="PIG_SPAWN_EGG">Pig Spawn Egg</option>
    <option value="PIGLIN_SPAWN_EGG">Piglin Spawn Egg</option>
    <option value="PIGLIN_BRUTE_SPAWN_EGG">Piglin Brute Spawn Egg</option>
    <option value="PILLAGER_SPAWN_EGG">Pillager Spawn Egg</option>
    <option value="POLAR_BEAR_SPAWN_EGG">Polar Bear Spawn Egg</option>
    <option value="PUFFERFISH_SPAWN_EGG">Pufferfish Spawn Egg</option>
    <option value="RABBIT_SPAWN_EGG">Rabbit Spawn Egg</option>
    <option value="RAVAGER_SPAWN_EGG">Ravager Spawn Egg</option>
    <option value="SALMON_SPAWN_EGG">Salmon Spawn Egg</option>
    <option value="SHEEP_SPAWN_EGG">Sheep Spawn Egg</option>
    <option value="SHULKER_SPAWN_EGG">Shulker Spawn Egg</option>
    <option value="SILVERFISH_SPAWN_EGG">Silverfish Spawn Egg</option>
    <option value="SKELETON_SPAWN_EGG">Skeleton Spawn Egg</option>
    <option value="SKELETON_HORSE_SPAWN_EGG">Skeleton Horse Spawn Egg</option>
    <option value="SLIME_SPAWN_EGG">Slime Spawn Egg</option>
    <option value="SPIDER_SPAWN_EGG">Spider Spawn Egg</option>
    <option value="SQUID_SPAWN_EGG">Squid Spawn Egg</option>
    <option value="STRAY_SPAWN_EGG">Stray Spawn Egg</option>
    <option value="STRIDER_SPAWN_EGG">Strider Spawn Egg</option>
    <option value="TADPOLE_SPAWN_EGG">Tadpole Spawn Egg</option>
    <option value="TRADER_LLAMA_SPAWN_EGG">Trader Llama Spawn Egg</option>
    <option value="TROPICAL_FISH_SPAWN_EGG">Tropical Fish Spawn Egg</option>
    <option value="TURTLE_SPAWN_EGG">Turtle Spawn Egg</option>
    <option value="VEX_SPAWN_EGG">Vex Spawn Egg</option>
    <option value="VILLAGER_SPAWN_EGG">Villager Spawn Egg</option>
    <option value="VINDICATOR_SPAWN_EGG">Vindicator Spawn Egg</option>
    <option value="WANDERING_TRADER_SPAWN_EGG">Wandering Trader Spawn Egg</option>
    <option value="WARDEN_SPAWN_EGG">Warden Spawn Egg</option>
    <option value="WITCH_SPAWN_EGG">Witch Spawn Egg</option>
    <option value="WITHER_SKELETON_SPAWN_EGG">Wither Skeleton Spawn Egg</option>
    <option value="WOLF_SPAWN_EGG">Wolf Spawn Egg</option>
    <option value="ZOGLIN_SPAWN_EGG">Zoglin Spawn Egg</option>
    <option value="ZOMBIE_SPAWN_EGG">Zombie Spawn Egg</option>
    <option value="ZOMBIE_HORSE_SPAWN_EGG">Zombie Horse Spawn Egg</option>
    <option value="ZOMBIE_VILLAGER_SPAWN_EGG">Zombie Villager Spawn Egg</option>
    <option value="ZOMBIFIED_PIGLIN_SPAWN_EGG">Zombified Piglin Spawn Egg</option>
    <option value="EXPERIENCE_BOTTLE">Experience Bottle</option>
    <option value="FIRE_CHARGE">Fire Charge</option>
    <option value="WRITABLE_BOOK">Writable Book</option>
    <option value="WRITTEN_BOOK">Written Book</option>
    <option value="ITEM_FRAME">Item Frame</option>
    <option value="GLOW_ITEM_FRAME">Glow Item Frame</option>
    <option value="FLOWER_POT">Flower Pot</option>
    <option value="CARROT">Carrot</option>
    <option value="POTATO">Potato</option>
    <option value="BAKED_POTATO">Baked Potato</option>
    <option value="POISONOUS_POTATO">Poisonous Potato</option>
    <option value="MAP">Map</option>
    <option value="GOLDEN_CARROT">Golden Carrot</option>
    <option value="SKELETON_SKULL">Skeleton Skull</option>
    <option value="WITHER_SKELETON_SKULL">Wither Skeleton Skull</option>
    <option value="PLAYER_HEAD">Player Head</option>
    <option value="ZOMBIE_HEAD">Zombie Head</option>
    <option value="CREEPER_HEAD">Creeper Head</option>
    <option value="DRAGON_HEAD">Dragon Head</option>
    <option value="NETHER_STAR">Nether Star</option>
    <option value="PUMPKIN_PIE">Pumpkin Pie</option>
    <option value="FIREWORK_ROCKET">Firework Rocket</option>
    <option value="FIREWORK_STAR">Firework Star</option>
    <option value="ENCHANTED_BOOK">Enchanted Book</option>
    <option value="NETHER_BRICK">Nether Brick</option>
    <option value="PRISMARINE_SHARD">Prismarine Shard</option>
    <option value="PRISMARINE_CRYSTALS">Prismarine Crystals</option>
    <option value="RABBIT">Rabbit</option>
    <option value="COOKED_RABBIT">Cooked Rabbit</option>
    <option value="RABBIT_STEW">Rabbit Stew</option>
    <option value="RABBIT_FOOT">Rabbit Foot</option>
    <option value="RABBIT_HIDE">Rabbit Hide</option>
    <option value="ARMOR_STAND">Armor Stand</option>
    <option value="IRON_HORSE_ARMOR">Iron Horse Armor</option>
    <option value="GOLDEN_HORSE_ARMOR">Golden Horse Armor</option>
    <option value="DIAMOND_HORSE_ARMOR">Diamond Horse Armor</option>
    <option value="LEATHER_HORSE_ARMOR">Leather Horse Armor</option>
    <option value="LEAD">Lead</option>
    <option value="NAME_TAG">Name Tag</option>
    <option value="COMMAND_BLOCK_MINECART">Command Block Minecart</option>
    <option value="MUTTON">Mutton</option>
    <option value="COOKED_MUTTON">Cooked Mutton</option>
    <option value="WHITE_BANNER">White Banner</option>
    <option value="ORANGE_BANNER">Orange Banner</option>
    <option value="MAGENTA_BANNER">Magenta Banner</option>
    <option value="LIGHT_BLUE_BANNER">Light Blue Banner</option>
    <option value="YELLOW_BANNER">Yellow Banner</option>
    <option value="LIME_BANNER">Lime Banner</option>
    <option value="PINK_BANNER">Pink Banner</option>
    <option value="GRAY_BANNER">Gray Banner</option>
    <option value="LIGHT_GRAY_BANNER">Light Gray Banner</option>
    <option value="CYAN_BANNER">Cyan Banner</option>
    <option value="PURPLE_BANNER">Purple Banner</option>
    <option value="BLUE_BANNER">Blue Banner</option>
    <option value="BROWN_BANNER">Brown Banner</option>
    <option value="GREEN_BANNER">Green Banner</option>
    <option value="RED_BANNER">Red Banner</option>
    <option value="BLACK_BANNER">Black Banner</option>
    <option value="END_CRYSTAL">End Crystal</option>
    <option value="CHORUS_FRUIT">Chorus Fruit</option>
    <option value="POPPED_CHORUS_FRUIT">Popped Chorus Fruit</option>
    <option value="BEETROOT">Beetroot</option>
    <option value="BEETROOT_SEEDS">Beetroot Seeds</option>
    <option value="BEETROOT_SOUP">Beetroot Soup</option>
    <option value="DRAGON_BREATH">Dragon Breath</option>
    <option value="SPLASH_POTION">Splash Potion</option>
    <option value="SPECTRAL_ARROW">Spectral Arrow</option>
    <option value="TIPPED_ARROW">Tipped Arrow</option>
    <option value="LINGERING_POTION">Lingering Potion</option>
    <option value="SHIELD">Shield</option>
    <option value="TOTEM_OF_UNDYING">Totem Of Undying</option>
    <option value="SHULKER_SHELL">Shulker Shell</option>
    <option value="IRON_NUGGET">Iron Nugget</option>
    <option value="KNOWLEDGE_BOOK">Knowledge Book</option>
    <option value="DEBUG_STICK">Debug Stick</option>
    <option value="MUSIC_DISC_13">Music Disc 13</option>
    <option value="MUSIC_DISC_CAT">Music Disc Cat</option>
    <option value="MUSIC_DISC_BLOCKS">Music Disc Blocks</option>
    <option value="MUSIC_DISC_CHIRP">Music Disc Chirp</option>
    <option value="MUSIC_DISC_FAR">Music Disc Far</option>
    <option value="MUSIC_DISC_MALL">Music Disc Mall</option>
    <option value="MUSIC_DISC_MELLOHI">Music Disc Mellohi</option>
    <option value="MUSIC_DISC_STAL">Music Disc Stal</option>
    <option value="MUSIC_DISC_STRAD">Music Disc Strad</option>
    <option value="MUSIC_DISC_WARD">Music Disc Ward</option>
    <option value="MUSIC_DISC_11">Music Disc 11</option>
    <option value="MUSIC_DISC_WAIT">Music Disc Wait</option>
    <option value="MUSIC_DISC_OTHERSIDE">Music Disc Otherside</option>
    <option value="MUSIC_DISC_5">Music Disc 5</option>
    <option value="MUSIC_DISC_PIGSTEP">Music Disc Pigstep</option>
    <option value="DISC_FRAGMENT_5">Disc Fragment 5</option>
    <option value="TRIDENT">Trident</option>
    <option value="PHANTOM_MEMBRANE">Phantom Membrane</option>
    <option value="NAUTILUS_SHELL">Nautilus Shell</option>
    <option value="HEART_OF_THE_SEA">Heart Of The Sea</option>
    <option value="CROSSBOW">Crossbow</option>
    <option value="SUSPICIOUS_STEW">Suspicious Stew</option>
    <option value="LOOM">Loom</option>
    <option value="FLOWER_BANNER_PATTERN">Flower Banner Pattern</option>
    <option value="CREEPER_BANNER_PATTERN">Creeper Banner Pattern</option>
    <option value="SKULL_BANNER_PATTERN">Skull Banner Pattern</option>
    <option value="MOJANG_BANNER_PATTERN">Mojang Banner Pattern</option>
    <option value="GLOBE_BANNER_PATTERN">Globe Banner Pattern</option>
    <option value="PIGLIN_BANNER_PATTERN">Piglin Banner Pattern</option>
    <option value="GOAT_HORN">Goat Horn</option>
    <option value="COMPOSTER">Composter</option>
    <option value="BARREL">Barrel</option>
    <option value="SMOKER">Smoker</option>
    <option value="BLAST_FURNACE">Blast Furnace</option>
    <option value="CARTOGRAPHY_TABLE">Cartography Table</option>
    <option value="FLETCHING_TABLE">Fletching Table</option>
    <option value="GRINDSTONE">Grindstone</option>
    <option value="SMITHING_TABLE">Smithing Table</option>
    <option value="STONECUTTER">Stonecutter</option>
    <option value="BELL">Bell</option>
    <option value="LANTERN">Lantern</option>
    <option value="SOUL_LANTERN">Soul Lantern</option>
    <option value="SWEET_BERRIES">Sweet Berries</option>
    <option value="GLOW_BERRIES">Glow Berries</option>
    <option value="CAMPFIRE">Campfire</option>
    <option value="SOUL_CAMPFIRE">Soul Campfire</option>
    <option value="SHROOMLIGHT">Shroomlight</option>
    <option value="HONEYCOMB">Honeycomb</option>
    <option value="BEE_NEST">Bee Nest</option>
    <option value="BEEHIVE">Beehive</option>
    <option value="HONEY_BOTTLE">Honey Bottle</option>
    <option value="HONEYCOMB_BLOCK">Honeycomb Block</option>
    <option value="LODESTONE">Lodestone</option>
    <option value="CRYING_OBSIDIAN">Crying Obsidian</option>
    <option value="BLACKSTONE">Blackstone</option>
    <option value="BLACKSTONE_SLAB">Blackstone Slab</option>
    <option value="BLACKSTONE_STAIRS">Blackstone Stairs</option>
    <option value="GILDED_BLACKSTONE">Gilded Blackstone</option>
    <option value="POLISHED_BLACKSTONE">Polished Blackstone</option>
    <option value="POLISHED_BLACKSTONE_SLAB">Polished Blackstone Slab</option>
    <option value="POLISHED_BLACKSTONE_STAIRS">Polished Blackstone Stairs</option>
    <option value="CHISELED_POLISHED_BLACKSTONE">Chiseled Polished Blackstone</option>
    <option value="POLISHED_BLACKSTONE_BRICKS">Polished Blackstone Bricks</option>
    <option value="POLISHED_BLACKSTONE_BRICK_SLAB">Polished Blackstone Brick Slab</option>
    <option value="POLISHED_BLACKSTONE_BRICK_STAIRS">Polished Blackstone Brick Stairs</option>
    <option value="CRACKED_POLISHED_BLACKSTONE_BRICKS">Cracked Polished Blackstone Bricks</option>
    <option value="RESPAWN_ANCHOR">Respawn Anchor</option>
    <option value="CANDLE">Candle</option>
    <option value="WHITE_CANDLE">White Candle</option>
    <option value="ORANGE_CANDLE">Orange Candle</option>
    <option value="MAGENTA_CANDLE">Magenta Candle</option>
    <option value="LIGHT_BLUE_CANDLE">Light Blue Candle</option>
    <option value="YELLOW_CANDLE">Yellow Candle</option>
    <option value="LIME_CANDLE">Lime Candle</option>
    <option value="PINK_CANDLE">Pink Candle</option>
    <option value="GRAY_CANDLE">Gray Candle</option>
    <option value="LIGHT_GRAY_CANDLE">Light Gray Candle</option>
    <option value="CYAN_CANDLE">Cyan Candle</option>
    <option value="PURPLE_CANDLE">Purple Candle</option>
    <option value="BLUE_CANDLE">Blue Candle</option>
    <option value="BROWN_CANDLE">Brown Candle</option>
    <option value="GREEN_CANDLE">Green Candle</option>
    <option value="RED_CANDLE">Red Candle</option>
    <option value="BLACK_CANDLE">Black Candle</option>
    <option value="SMALL_AMETHYST_BUD">Small Amethyst Bud</option>
    <option value="MEDIUM_AMETHYST_BUD">Medium Amethyst Bud</option>
    <option value="LARGE_AMETHYST_BUD">Large Amethyst Bud</option>
    <option value="AMETHYST_CLUSTER">Amethyst Cluster</option>
    <option value="POINTED_DRIPSTONE">Pointed Dripstone</option>
    <option value="OCHRE_FROGLIGHT">Ochre Froglight</option>
    <option value="VERDANT_FROGLIGHT">Verdant Froglight</option>
    <option value="PEARLESCENT_FROGLIGHT">Pearlescent Froglight</option>
    <option value="FROGSPAWN">Frogspawn</option>
    <option value="ECHO_SHARD">Echo Shard</option>
    <option value="WATER">Water</option>
    <option value="LAVA">Lava</option>
    <option value="TALL_SEAGRASS">Tall Seagrass</option>
    <option value="PISTON_HEAD">Piston Head</option>
    <option value="MOVING_PISTON">Moving Piston</option>
    <option value="WALL_TORCH">Wall Torch</option>
    <option value="FIRE">Fire</option>
    <option value="SOUL_FIRE">Soul Fire</option>
    <option value="REDSTONE_WIRE">Redstone Wire</option>
    <option value="OAK_WALL_SIGN">Oak Wall Sign</option>
    <option value="SPRUCE_WALL_SIGN">Spruce Wall Sign</option>
    <option value="BIRCH_WALL_SIGN">Birch Wall Sign</option>
    <option value="ACACIA_WALL_SIGN">Acacia Wall Sign</option>
    <option value="JUNGLE_WALL_SIGN">Jungle Wall Sign</option>
    <option value="DARK_OAK_WALL_SIGN">Dark Oak Wall Sign</option>
    <option value="MANGROVE_WALL_SIGN">Mangrove Wall Sign</option>
    <option value="REDSTONE_WALL_TORCH">Redstone Wall Torch</option>
    <option value="SOUL_WALL_TORCH">Soul Wall Torch</option>
    <option value="NETHER_PORTAL">Nether Portal</option>
    <option value="ATTACHED_PUMPKIN_STEM">Attached Pumpkin Stem</option>
    <option value="ATTACHED_MELON_STEM">Attached Melon Stem</option>
    <option value="PUMPKIN_STEM">Pumpkin Stem</option>
    <option value="MELON_STEM">Melon Stem</option>
    <option value="WATER_CAULDRON">Water Cauldron</option>
    <option value="LAVA_CAULDRON">Lava Cauldron</option>
    <option value="POWDER_SNOW_CAULDRON">Powder Snow Cauldron</option>
    <option value="END_PORTAL">End Portal</option>
    <option value="COCOA">Cocoa</option>
    <option value="TRIPWIRE">Tripwire</option>
    <option value="POTTED_OAK_SAPLING">Potted Oak Sapling</option>
    <option value="POTTED_SPRUCE_SAPLING">Potted Spruce Sapling</option>
    <option value="POTTED_BIRCH_SAPLING">Potted Birch Sapling</option>
    <option value="POTTED_JUNGLE_SAPLING">Potted Jungle Sapling</option>
    <option value="POTTED_ACACIA_SAPLING">Potted Acacia Sapling</option>
    <option value="POTTED_DARK_OAK_SAPLING">Potted Dark Oak Sapling</option>
    <option value="POTTED_MANGROVE_PROPAGULE">Potted Mangrove Propagule</option>
    <option value="POTTED_FERN">Potted Fern</option>
    <option value="POTTED_DANDELION">Potted Dandelion</option>
    <option value="POTTED_POPPY">Potted Poppy</option>
    <option value="POTTED_BLUE_ORCHID">Potted Blue Orchid</option>
    <option value="POTTED_ALLIUM">Potted Allium</option>
    <option value="POTTED_AZURE_BLUET">Potted Azure Bluet</option>
    <option value="POTTED_RED_TULIP">Potted Red Tulip</option>
    <option value="POTTED_ORANGE_TULIP">Potted Orange Tulip</option>
    <option value="POTTED_WHITE_TULIP">Potted White Tulip</option>
    <option value="POTTED_PINK_TULIP">Potted Pink Tulip</option>
    <option value="POTTED_OXEYE_DAISY">Potted Oxeye Daisy</option>
    <option value="POTTED_CORNFLOWER">Potted Cornflower</option>
    <option value="POTTED_LILY_OF_THE_VALLEY">Potted Lily Of The Valley</option>
    <option value="POTTED_WITHER_ROSE">Potted Wither Rose</option>
    <option value="POTTED_RED_MUSHROOM">Potted Red Mushroom</option>
    <option value="POTTED_BROWN_MUSHROOM">Potted Brown Mushroom</option>
    <option value="POTTED_DEAD_BUSH">Potted Dead Bush</option>
    <option value="POTTED_CACTUS">Potted Cactus</option>
    <option value="CARROTS">Carrots</option>
    <option value="POTATOES">Potatoes</option>
    <option value="SKELETON_WALL_SKULL">Skeleton Wall Skull</option>
    <option value="WITHER_SKELETON_WALL_SKULL">Wither Skeleton Wall Skull</option>
    <option value="ZOMBIE_WALL_HEAD">Zombie Wall Head</option>
    <option value="PLAYER_WALL_HEAD">Player Wall Head</option>
    <option value="CREEPER_WALL_HEAD">Creeper Wall Head</option>
    <option value="DRAGON_WALL_HEAD">Dragon Wall Head</option>
    <option value="WHITE_WALL_BANNER">White Wall Banner</option>
    <option value="ORANGE_WALL_BANNER">Orange Wall Banner</option>
    <option value="MAGENTA_WALL_BANNER">Magenta Wall Banner</option>
    <option value="LIGHT_BLUE_WALL_BANNER">Light Blue Wall Banner</option>
    <option value="YELLOW_WALL_BANNER">Yellow Wall Banner</option>
    <option value="LIME_WALL_BANNER">Lime Wall Banner</option>
    <option value="PINK_WALL_BANNER">Pink Wall Banner</option>
    <option value="GRAY_WALL_BANNER">Gray Wall Banner</option>
    <option value="LIGHT_GRAY_WALL_BANNER">Light Gray Wall Banner</option>
    <option value="CYAN_WALL_BANNER">Cyan Wall Banner</option>
    <option value="PURPLE_WALL_BANNER">Purple Wall Banner</option>
    <option value="BLUE_WALL_BANNER">Blue Wall Banner</option>
    <option value="BROWN_WALL_BANNER">Brown Wall Banner</option>
    <option value="GREEN_WALL_BANNER">Green Wall Banner</option>
    <option value="RED_WALL_BANNER">Red Wall Banner</option>
    <option value="BLACK_WALL_BANNER">Black Wall Banner</option>
    <option value="BEETROOTS">Beetroots</option>
    <option value="END_GATEWAY">End Gateway</option>
    <option value="FROSTED_ICE">Frosted Ice</option>
    <option value="KELP_PLANT">Kelp Plant</option>
    <option value="DEAD_TUBE_CORAL_WALL_FAN">Dead Tube Coral Wall Fan</option>
    <option value="DEAD_BRAIN_CORAL_WALL_FAN">Dead Brain Coral Wall Fan</option>
    <option value="DEAD_BUBBLE_CORAL_WALL_FAN">Dead Bubble Coral Wall Fan</option>
    <option value="DEAD_FIRE_CORAL_WALL_FAN">Dead Fire Coral Wall Fan</option>
    <option value="DEAD_HORN_CORAL_WALL_FAN">Dead Horn Coral Wall Fan</option>
    <option value="TUBE_CORAL_WALL_FAN">Tube Coral Wall Fan</option>
    <option value="BRAIN_CORAL_WALL_FAN">Brain Coral Wall Fan</option>
    <option value="BUBBLE_CORAL_WALL_FAN">Bubble Coral Wall Fan</option>
    <option value="FIRE_CORAL_WALL_FAN">Fire Coral Wall Fan</option>
    <option value="HORN_CORAL_WALL_FAN">Horn Coral Wall Fan</option>
    <option value="BAMBOO_SAPLING">Bamboo Sapling</option>
    <option value="POTTED_BAMBOO">Potted Bamboo</option>
    <option value="BUBBLE_COLUMN">Bubble Column</option>
    <option value="SWEET_BERRY_BUSH">Sweet Berry Bush</option>
    <option value="WEEPING_VINES_PLANT">Weeping Vines Plant</option>
    <option value="TWISTING_VINES_PLANT">Twisting Vines Plant</option>
    <option value="CRIMSON_WALL_SIGN">Crimson Wall Sign</option>
    <option value="WARPED_WALL_SIGN">Warped Wall Sign</option>
    <option value="POTTED_CRIMSON_FUNGUS">Potted Crimson Fungus</option>
    <option value="POTTED_WARPED_FUNGUS">Potted Warped Fungus</option>
    <option value="POTTED_CRIMSON_ROOTS">Potted Crimson Roots</option>
    <option value="POTTED_WARPED_ROOTS">Potted Warped Roots</option>
    <option value="CANDLE_CAKE">Candle Cake</option>
    <option value="WHITE_CANDLE_CAKE">White Candle Cake</option>
    <option value="ORANGE_CANDLE_CAKE">Orange Candle Cake</option>
    <option value="MAGENTA_CANDLE_CAKE">Magenta Candle Cake</option>
    <option value="LIGHT_BLUE_CANDLE_CAKE">Light Blue Candle Cake</option>
    <option value="YELLOW_CANDLE_CAKE">Yellow Candle Cake</option>
    <option value="LIME_CANDLE_CAKE">Lime Candle Cake</option>
    <option value="PINK_CANDLE_CAKE">Pink Candle Cake</option>
    <option value="GRAY_CANDLE_CAKE">Gray Candle Cake</option>
    <option value="LIGHT_GRAY_CANDLE_CAKE">Light Gray Candle Cake</option>
    <option value="CYAN_CANDLE_CAKE">Cyan Candle Cake</option>
    <option value="PURPLE_CANDLE_CAKE">Purple Candle Cake</option>
    <option value="BLUE_CANDLE_CAKE">Blue Candle Cake</option>
    <option value="BROWN_CANDLE_CAKE">Brown Candle Cake</option>
    <option value="GREEN_CANDLE_CAKE">Green Candle Cake</option>
    <option value="RED_CANDLE_CAKE">Red Candle Cake</option>
    <option value="BLACK_CANDLE_CAKE">Black Candle Cake</option>
    <option value="POWDER_SNOW">Powder Snow</option>
    <option value="CAVE_VINES">Cave Vines</option>
    <option value="CAVE_VINES_PLANT">Cave Vines Plant</option>
    <option value="BIG_DRIPLEAF_STEM">Big Dripleaf Stem</option>
    <option value="POTTED_AZALEA_BUSH">Potted Azalea Bush</option>
    <option value="POTTED_FLOWERING_AZALEA_BUSH">Potted Flowering Azalea Bush</option>
</select>
