<script>
    import SelectProperty from './SelectProperty.svelte';

    export let name;
    export let value;
    export let small = false;
</script>

<SelectProperty {name} {small} options={[
    {name: 'Explosion Normal', value: 'EXPLOSION_NORMAL'},
    {name: 'Explosion Large', value: 'EXPLOSION_LARGE'},
    {name: 'Explosion Huge', value: 'EXPLOSION_HUGE'},
    {name: 'Fireworks Spark', value: 'FIREWORKS_SPARK'},
    {name: 'Water Bubble', value: 'WATER_BUBBLE'},
    {name: 'Water Splash', value: 'WATER_SPLASH'},
    {name: 'Water Wake', value: 'WATER_WAKE'},
    {name: 'Suspended', value: 'SUSPENDED'},
    {name: 'Suspended Depth', value: 'SUSPENDED_DEPTH'},
    {name: 'Crit', value: 'CRIT'},
    {name: 'Crit Magic', value: 'CRIT_MAGIC'},
    {name: 'Smoke Normal', value: 'SMOKE_NORMAL'},
    {name: 'Smoke Large', value: 'SMOKE_LARGE'},
    {name: 'Spell', value: 'SPELL'},
    {name: 'Spell Instant', value: 'SPELL_INSTANT'},
    {name: 'Spell Mob', value: 'SPELL_MOB'},
    {name: 'Spell Mob Ambient', value: 'SPELL_MOB_AMBIENT'},
    {name: 'Spell Witch', value: 'SPELL_WITCH'},
    {name: 'Drip Water', value: 'DRIP_WATER'},
    {name: 'Drip Lava', value: 'DRIP_LAVA'},
    {name: 'Villager Angry', value: 'VILLAGER_ANGRY'},
    {name: 'Villager Happy', value: 'VILLAGER_HAPPY'},
    {name: 'Town Aura', value: 'TOWN_AURA'},
    {name: 'Note', value: 'NOTE'},
    {name: 'Portal', value: 'PORTAL'},
    {name: 'Enchantment Table', value: 'ENCHANTMENT_TABLE'},
    {name: 'Flame', value: 'FLAME'},
    {name: 'Lava', value: 'LAVA'},
    {name: 'Cloud', value: 'CLOUD'},
    {name: 'Redstone', value: 'REDSTONE'},
    {name: 'Snowball', value: 'SNOWBALL'},
    {name: 'Snow Shovel', value: 'SNOW_SHOVEL'},
    {name: 'Slime', value: 'SLIME'},
    {name: 'Heart', value: 'HEART'},
    {name: 'Item Crack', value: 'ITEM_CRACK'},
    {name: 'Block Crack', value: 'BLOCK_CRACK'},
    {name: 'Block Dust', value: 'BLOCK_DUST'},
    {name: 'Water Drop', value: 'WATER_DROP'},
    {name: 'Mob Appearance', value: 'MOB_APPEARANCE'},
    {name: 'Dragon Breath', value: 'DRAGON_BREATH'},
    {name: 'End Rod', value: 'END_ROD'},
    {name: 'Damage Indicator', value: 'DAMAGE_INDICATOR'},
    {name: 'Sweep Attack', value: 'SWEEP_ATTACK'},
    {name: 'Falling Dust', value: 'FALLING_DUST'},
    {name: 'Totem', value: 'TOTEM'},
    {name: 'Spit', value: 'SPIT'},
    {name: 'Squid Ink', value: 'SQUID_INK'},
    {name: 'Bubble Pop', value: 'BUBBLE_POP'},
    {name: 'Current Down', value: 'CURRENT_DOWN'},
    {name: 'Bubble Column Up', value: 'BUBBLE_COLUMN_UP'},
    {name: 'Nautilus', value: 'NAUTILUS'},
    {name: 'Dolphin', value: 'DOLPHIN'},
    {name: 'Sneeze', value: 'SNEEZE'},
    {name: 'Campfire Cosy Smoke', value: 'CAMPFIRE_COSY_SMOKE'},
    {name: 'Campfire Signal Smoke', value: 'CAMPFIRE_SIGNAL_SMOKE'},
    {name: 'Composter', value: 'COMPOSTER'},
    {name: 'Flash', value: 'FLASH'},
    {name: 'Falling Lava', value: 'FALLING_LAVA'},
    {name: 'Landing Lava', value: 'LANDING_LAVA'},
    {name: 'Falling Water', value: 'FALLING_WATER'},
    {name: 'Dripping Honey', value: 'DRIPPING_HONEY'},
    {name: 'Falling Honey', value: 'FALLING_HONEY'},
    {name: 'Landing Honey', value: 'LANDING_HONEY'},
    {name: 'Falling Nectar', value: 'FALLING_NECTAR'},
    {name: 'Soul Fire Flame', value: 'SOUL_FIRE_FLAME'},
    {name: 'Ash', value: 'ASH'},
    {name: 'Crimson Spore', value: 'CRIMSON_SPORE'},
    {name: 'Warped Spore', value: 'WARPED_SPORE'},
    {name: 'Soul', value: 'SOUL'},
    {name: 'Dripping Obsidian Tear', value: 'DRIPPING_OBSIDIAN_TEAR'},
    {name: 'Falling Obsidian Tear', value: 'FALLING_OBSIDIAN_TEAR'},
    {name: 'Landing Obsidian Tear', value: 'LANDING_OBSIDIAN_TEAR'},
    {name: 'Reverse Portal', value: 'REVERSE_PORTAL'},
    {name: 'White Ash', value: 'WHITE_ASH'},
    {name: 'Vibration', value: 'VIBRATION'},
    {name: 'Falling Spore Blossom', value: 'FALLING_SPORE_BLOSSOM'},
    {name: 'Spore Blossom Air', value: 'SPORE_BLOSSOM_AIR'},
    {name: 'Small Flame', value: 'SMALL_FLAME'},
    {name: 'Snowflake', value: 'SNOWFLAKE'},
    {name: 'Dripping Dripstone Lava', value: 'DRIPPING_DRIPSTONE_LAVA'},
    {name: 'Falling Dripstone Lava', value: 'FALLING_DRIPSTONE_LAVA'},
    {name: 'Dripping Dripstone Water', value: 'DRIPPING_DRIPSTONE_WATER'},
    {name: 'Falling Dripstone Water', value: 'FALLING_DRIPSTONE_WATER'},
    {name: 'Glow Squid Ink', value: 'GLOW_SQUID_INK'},
    {name: 'Glow', value: 'GLOW'},
    {name: 'Wax On', value: 'WAX_ON'},
    {name: 'Wax Off', value: 'WAX_OFF'},
    {name: 'Electric Spark', value: 'ELECTRIC_SPARK'},
    {name: 'Scrape', value: 'SCRAPE'},
    {name: 'Sonic Boom', value: 'SONIC_BOOM'},
    {name: 'Sculk Soul', value: 'SCULK_SOUL'},
    {name: 'Sculk Charge', value: 'SCULK_CHARGE'},
    {name: 'Sculk Charge Pop', value: 'SCULK_CHARGE_POP'},
    {name: 'Shriek', value: 'SHRIEK'}
]} bind:value><slot/></SelectProperty>
