<script>
    import SelectProperty from './SelectProperty.svelte';

    export let value;
</script>

<SelectProperty {...$$restProps} options={{
    'Explosion Normal': 'EXPLOSION_NORMAL',
    'Explosion Large': 'EXPLOSION_LARGE',
    'Explosion Huge': 'EXPLOSION_HUGE',
    'Fireworks Spark': 'FIREWORKS_SPARK',
    'Water Bubble': 'WATER_BUBBLE',
    'Water Splash': 'WATER_SPLASH',
    'Water Wake': 'WATER_WAKE',
    'Suspended': 'SUSPENDED',
    'Suspended Depth': 'SUSPENDED_DEPTH',
    'Crit': 'CRIT',
    'Crit Magic': 'CRIT_MAGIC',
    'Smoke Normal': 'SMOKE_NORMAL',
    'Smoke Large': 'SMOKE_LARGE',
    'Spell': 'SPELL',
    'Spell Instant': 'SPELL_INSTANT',
    'Spell Mob': 'SPELL_MOB',
    'Spell Mob Ambient': 'SPELL_MOB_AMBIENT',
    'Spell Witch': 'SPELL_WITCH',
    'Drip Water': 'DRIP_WATER',
    'Drip Lava': 'DRIP_LAVA',
    'Villager Angry': 'VILLAGER_ANGRY',
    'Villager Happy': 'VILLAGER_HAPPY',
    'Town Aura': 'TOWN_AURA',
    'Note': 'NOTE',
    'Portal': 'PORTAL',
    'Enchantment Table': 'ENCHANTMENT_TABLE',
    'Flame': 'FLAME',
    'Lava': 'LAVA',
    'Cloud': 'CLOUD',
    'Redstone': 'REDSTONE',
    'Snowball': 'SNOWBALL',
    'Snow Shovel': 'SNOW_SHOVEL',
    'Slime': 'SLIME',
    'Heart': 'HEART',
    'Item Crack': 'ITEM_CRACK',
    'Block Crack': 'BLOCK_CRACK',
    'Block Dust': 'BLOCK_DUST',
    'Water Drop': 'WATER_DROP',
    'Mob Appearance': 'MOB_APPEARANCE',
    'Dragon Breath': 'DRAGON_BREATH',
    'End Rod': 'END_ROD',
    'Damage Indicator': 'DAMAGE_INDICATOR',
    'Sweep Attack': 'SWEEP_ATTACK',
    'Falling Dust': 'FALLING_DUST',
    'Totem': 'TOTEM',
    'Spit': 'SPIT',
    'Squid Ink': 'SQUID_INK',
    'Bubble Pop': 'BUBBLE_POP',
    'Current Down': 'CURRENT_DOWN',
    'Bubble Column Up': 'BUBBLE_COLUMN_UP',
    'Nautilus': 'NAUTILUS',
    'Dolphin': 'DOLPHIN',
    'Sneeze': 'SNEEZE',
    'Campfire Cosy Smoke': 'CAMPFIRE_COSY_SMOKE',
    'Campfire Signal Smoke': 'CAMPFIRE_SIGNAL_SMOKE',
    'Composter': 'COMPOSTER',
    'Flash': 'FLASH',
    'Falling Lava': 'FALLING_LAVA',
    'Landing Lava': 'LANDING_LAVA',
    'Falling Water': 'FALLING_WATER',
    'Dripping Honey': 'DRIPPING_HONEY',
    'Falling Honey': 'FALLING_HONEY',
    'Landing Honey': 'LANDING_HONEY',
    'Falling Nectar': 'FALLING_NECTAR',
    'Soul Fire Flame': 'SOUL_FIRE_FLAME',
    'Ash': 'ASH',
    'Crimson Spore': 'CRIMSON_SPORE',
    'Warped Spore': 'WARPED_SPORE',
    'Soul': 'SOUL',
    'Dripping Obsidian Tear': 'DRIPPING_OBSIDIAN_TEAR',
    'Falling Obsidian Tear': 'FALLING_OBSIDIAN_TEAR',
    'Landing Obsidian Tear': 'LANDING_OBSIDIAN_TEAR',
    'Reverse Portal': 'REVERSE_PORTAL',
    'White Ash': 'WHITE_ASH',
    'Dust Color Transition': 'DUST_COLOR_TRANSITION',
    'Vibration': 'VIBRATION',
    'Falling Spore Blossom': 'FALLING_SPORE_BLOSSOM',
    'Spore Blossom Air': 'SPORE_BLOSSOM_AIR',
    'Small Flame': 'SMALL_FLAME',
    'Snowflake': 'SNOWFLAKE',
    'Dripping Dripstone Lava': 'DRIPPING_DRIPSTONE_LAVA',
    'Falling Dripstone Lava': 'FALLING_DRIPSTONE_LAVA',
    'Dripping Dripstone Water': 'DRIPPING_DRIPSTONE_WATER',
    'Falling Dripstone Water': 'FALLING_DRIPSTONE_WATER',
    'Glow Squid Ink': 'GLOW_SQUID_INK',
    'Glow': 'GLOW',
    'Wax On': 'WAX_ON',
    'Wax Off': 'WAX_OFF',
    'Electric Spark': 'ELECTRIC_SPARK',
    'Scrape': 'SCRAPE',
    'Sonic Boom': 'SONIC_BOOM',
    'Sculk Soul': 'SCULK_SOUL',
    'Sculk Charge': 'SCULK_CHARGE',
    'Sculk Charge Pop': 'SCULK_CHARGE_POP',
    'Shriek': 'SHRIEK',
    'Block Marker': 'BLOCK_MARKER'
}} bind:value><slot/></SelectProperty>
